-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- +goose StatementBegin
CREATE FUNCTION public.notify_sim_result()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM
        pg_notify('new_sim_result', NEW.id::text);
    RETURN NEW;
END;
$$;

-- +goose StatementEnd
-- +goose StatementBegin
CREATE FUNCTION public.notify_simulation_data()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM
        pg_notify('new_simulation_data', NEW.id::text);
    RETURN NEW;
END;
$$;

-- +goose StatementEnd
-- +goose StatementBegin
CREATE FUNCTION public.update_timestamp()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TYPE principal_type AS ENUM(
    'user',
    'service'
);

CREATE TYPE simulation_status AS ENUM(
    'in_progress', -- currently being performed
    'in_queue', -- waiting to be picked up and in queue
    'error', -- failed
    'complete'
);

-- services principal table. Each row here represents
-- a backend service.
CREATE TABLE public.services(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name text NOT NULL UNIQUE
);

-- principal (owner) of an API key. We have user-owned API keys,
-- and we have internal services that use API keys.
CREATE TABLE public.principals(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    service_id uuid,
    user_id text,
    principal_type principal_type NOT NULL,
    CONSTRAINT principals_type_matches_owner CHECK ((principal_type = 'service' AND service_id IS NOT NULL AND user_id IS NULL) OR (principal_type = 'user' AND user_id IS NOT NULL AND service_id IS NULL)),
    CONSTRAINT fk_principal_service FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE,
    CONSTRAINT fk_principal_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE
);

-- +goose StatementEnd
CREATE TABLE public.api_keys(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- last time the key was used
    last_used_at timestamptz,
    -- non-secret portion shown in logs and admin UIs
    visible_hint text NOT NULL,
    -- SHA256 hash of the raw API key
    secret_hash text NOT NULL UNIQUE,
    -- principal who owns this key, if associated with a user account
    principal_id uuid NOT NULL,
    CONSTRAINT fk_api_key_principal_owner FOREIGN KEY (principal_id) REFERENCES public.principals(id) ON DELETE CASCADE
);

CREATE TABLE public.simulation(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id text,
    status simulation_status NOT NULL DEFAULT 'in_queue',
    sim_config jsonb NOT NULL,
    sim_result text,
    error_text text,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    CONSTRAINT fk_simulation_owner_id FOREIGN KEY (owner_id) REFERENCES public.user(id) ON DELETE SET NULL
);

CREATE TRIGGER new_sim_result
    AFTER INSERT ON public.simulation
    FOR EACH ROW
    WHEN(NEW.sim_result IS NOT NULL OR NEW.error_text IS NOT NULL OR NEW.completed_at IS NOT NULL)
    EXECUTE FUNCTION public.notify_sim_result();

CREATE TRIGGER new_simulation_data
    AFTER INSERT ON public.simulation
    FOR EACH ROW
    WHEN(NEW.sim_result IS NOT NULL OR NEW.error_text IS NOT NULL OR NEW.completed_at IS NOT NULL)
    EXECUTE FUNCTION public.notify_simulation_data();

CREATE TRIGGER new_simulation_data_update
    AFTER UPDATE OF sim_result,
    error_text,
    completed_at ON public.simulation
    FOR EACH ROW
    WHEN(OLD.sim_result IS DISTINCT FROM NEW.sim_result OR OLD.error_text IS DISTINCT FROM NEW.error_text OR OLD.completed_at IS DISTINCT FROM NEW.completed_at)
    EXECUTE FUNCTION public.notify_simulation_data();

CREATE TRIGGER update_timestamp_trigger
    BEFORE UPDATE ON public.api_keys
    FOR EACH ROW
    EXECUTE FUNCTION public.update_timestamp();

-- seed services table and api keys
-- 1. insert service for discord_bot
INSERT INTO public.services(name)
    VALUES ('discord_bot');

-- 2. create corresponding principal entry for discord_bot
INSERT INTO public.principals(service_id, principal_type)
SELECT
    id,
    'service'::principal_type
FROM
    public.services
WHERE
    name = 'discord_bot';

-- 3. create API for for discord_bot
-- +goose ENVSUB ON
INSERT INTO public.api_keys(visible_hint, secret_hash, principal_id)
SELECT
    'sk_test_' ||
    LEFT ('${SAINT_API_KEY?SAINT_API_KEY must be set}',
        12),
    encode(digest('${SAINT_API_KEY?SAINT_API_KEY must be set}', 'sha256'), 'hex'),
    id
FROM
    public.principals
WHERE
    principal_type = 'service'::principal_type
    AND service_id =(
        SELECT
            id
        FROM
            public.services
        WHERE
            name = 'discord_bot');

-- +goose ENVSUB OFF
-- +goose Down
DROP TRIGGER IF EXISTS update_timestamp_trigger ON public.api_keys;

DROP TRIGGER IF EXISTS new_simulation_data_update ON public.simulation;

DROP TRIGGER IF EXISTS new_simulation_data ON public.simulation;

DROP TRIGGER IF EXISTS new_sim_result ON public.simulation;

DROP TABLE IF EXISTS public.simulation;

DROP TABLE IF EXISTS public.api_keys;

DROP TABLE IF EXISTS public.principals;

DROP TABLE IF EXISTS public.services;

DROP TYPE IF EXISTS principal_type;

DROP FUNCTION IF EXISTS public.update_timestamp();

DROP FUNCTION IF EXISTS public.notify_simulation_data();

DROP FUNCTION IF EXISTS public.notify_sim_result();
