-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- +goose StatementBegin
CREATE FUNCTION public.notify_sim_result() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('new_sim_result', NEW.id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.notify_simulation_data() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('new_simulation_data', NEW.id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TABLE public.api_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key character varying(255) NOT NULL,
    service_name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.simulation (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sim_config jsonb NOT NULL,
    sim_result text,
    error_text text,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz
);

CREATE TRIGGER new_sim_result
    AFTER INSERT ON public.simulation
    FOR EACH ROW
    WHEN (
        NEW.sim_result IS NOT NULL
        OR NEW.error_text IS NOT NULL
        OR NEW.completed_at IS NOT NULL
    )
    EXECUTE FUNCTION public.notify_sim_result();

CREATE TRIGGER new_simulation_data
    AFTER INSERT ON public.simulation
    FOR EACH ROW
    WHEN (
        NEW.sim_result IS NOT NULL
        OR NEW.error_text IS NOT NULL
        OR NEW.completed_at IS NOT NULL
    )
    EXECUTE FUNCTION public.notify_simulation_data();

CREATE TRIGGER new_simulation_data_update
    AFTER UPDATE OF sim_result, error_text, completed_at ON public.simulation
    FOR EACH ROW
    WHEN (
        OLD.sim_result IS DISTINCT FROM NEW.sim_result
        OR OLD.error_text IS DISTINCT FROM NEW.error_text
        OR OLD.completed_at IS DISTINCT FROM NEW.completed_at
    )
    EXECUTE FUNCTION public.notify_simulation_data();

CREATE TRIGGER update_timestamp_trigger
    BEFORE UPDATE ON public.api_keys
    FOR EACH ROW
    EXECUTE FUNCTION public.update_timestamp();

-- seed api key table with the env var
-- +goose ENVSUB ON
INSERT INTO public.api_keys (api_key, service_name)
VALUES ('${SAINT_API_KEY?SAINT_API_KEY must be set}', 'saint');
-- +goose ENVSUB OFF

-- +goose Down
DROP TRIGGER IF EXISTS update_timestamp_trigger ON public.api_keys;
DROP TRIGGER IF EXISTS new_simulation_data_update ON public.simulation;
DROP TRIGGER IF EXISTS new_simulation_data ON public.simulation;
DROP TRIGGER IF EXISTS new_sim_result ON public.simulation;

DROP TABLE IF EXISTS public.simulation;
DROP TABLE IF EXISTS public.api_keys;

DROP FUNCTION IF EXISTS public.update_timestamp();
DROP FUNCTION IF EXISTS public.notify_simulation_data();
DROP FUNCTION IF EXISTS public.notify_sim_result();
