-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- +goose StatementBegin
CREATE FUNCTION public.notify_sim_result() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('new_sim_result', NEW.id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.notify_simulation_data() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('new_simulation_data', NEW.request_id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TABLE public.api_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key character varying(255) NOT NULL,
    service_name character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.simulation_request (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
    received_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    options jsonb NOT NULL
);

CREATE TABLE public.simulation_data (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id uuid NOT NULL,
    sim_result text NOT NULL,
    CONSTRAINT simulation_data_request_id_fkey
        FOREIGN KEY (request_id) REFERENCES public.simulation_request(id) ON DELETE CASCADE
);

CREATE TRIGGER new_sim_result
    AFTER INSERT ON public.simulation_data
    FOR EACH ROW
    EXECUTE FUNCTION public.notify_sim_result();

CREATE TRIGGER new_simulation_data
    AFTER INSERT ON public.simulation_data
    FOR EACH ROW
    EXECUTE FUNCTION public.notify_simulation_data();

CREATE TRIGGER update_timestamp_trigger
    BEFORE UPDATE ON public.api_keys
    FOR EACH ROW
    EXECUTE FUNCTION public.update_timestamp();

-- +goose Down
DROP TRIGGER IF EXISTS update_timestamp_trigger ON public.api_keys;
DROP TRIGGER IF EXISTS new_simulation_data ON public.simulation_data;
DROP TRIGGER IF EXISTS new_sim_result ON public.simulation_data;

DROP TABLE IF EXISTS public.simulation_data;
DROP TABLE IF EXISTS public.simulation_request;
DROP TABLE IF EXISTS public.api_keys;

DROP FUNCTION IF EXISTS public.update_timestamp();
DROP FUNCTION IF EXISTS public.notify_simulation_data();
DROP FUNCTION IF EXISTS public.notify_sim_result();
