// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int32
	ApiKey      string
	ServiceName string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type SimulationDatum struct {
	ID        int32
	RequestID pgtype.UUID
	SimResult string
}

type SimulationRequest struct {
	ID         pgtype.UUID
	ReceivedAt pgtype.Timestamp
	Options    []byte
}
