// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSimulationRequest = `-- name: CreateSimulationRequest :exec
INSERT INTO public.simulation_request (id, options)
VALUES ($1, $2)
`

type CreateSimulationRequestParams struct {
	ID      pgtype.UUID
	Options []byte
}

func (q *Queries) CreateSimulationRequest(ctx context.Context, arg CreateSimulationRequestParams) error {
	_, err := q.db.Exec(ctx, createSimulationRequest, arg.ID, arg.Options)
	return err
}

const getApiKeyServiceName = `-- name: GetApiKeyServiceName :one
SELECT service_name
FROM public.api_keys
WHERE api_key = $1
LIMIT 1
`

func (q *Queries) GetApiKeyServiceName(ctx context.Context, apiKey string) (string, error) {
	row := q.db.QueryRow(ctx, getApiKeyServiceName, apiKey)
	var service_name string
	err := row.Scan(&service_name)
	return service_name, err
}

const getApiKeys = `-- name: GetApiKeys :one
SELECT id, api_key, service_name, created_at, updated_at FROM public.api_keys 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApiKeys(ctx context.Context, id int32) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeys, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.ServiceName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimulationData = `-- name: GetSimulationData :one
SELECT id, request_id, sim_result
FROM public.simulation_data
WHERE id = $1
`

func (q *Queries) GetSimulationData(ctx context.Context, id int32) (SimulationDatum, error) {
	row := q.db.QueryRow(ctx, getSimulationData, id)
	var i SimulationDatum
	err := row.Scan(&i.ID, &i.RequestID, &i.SimResult)
	return i, err
}

const getSimulationDataByRequestID = `-- name: GetSimulationDataByRequestID :one
SELECT id, request_id, sim_result
FROM public.simulation_data
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetSimulationDataByRequestID(ctx context.Context, requestID pgtype.UUID) (SimulationDatum, error) {
	row := q.db.QueryRow(ctx, getSimulationDataByRequestID, requestID)
	var i SimulationDatum
	err := row.Scan(&i.ID, &i.RequestID, &i.SimResult)
	return i, err
}

const getSimulationRequestOptions = `-- name: GetSimulationRequestOptions :one
SELECT options
FROM public.simulation_request
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSimulationRequestOptions(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSimulationRequestOptions, id)
	var options []byte
	err := row.Scan(&options)
	return options, err
}

const insertSimulationData = `-- name: InsertSimulationData :exec
INSERT INTO public.simulation_data (request_id, sim_result)
VALUES ($1, $2)
`

type InsertSimulationDataParams struct {
	RequestID pgtype.UUID
	SimResult string
}

func (q *Queries) InsertSimulationData(ctx context.Context, arg InsertSimulationDataParams) error {
	_, err := q.db.Exec(ctx, insertSimulationData, arg.RequestID, arg.SimResult)
	return err
}

const listenNewSimulationData = `-- name: ListenNewSimulationData :exec
LISTEN new_simulation_data
`

func (q *Queries) ListenNewSimulationData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, listenNewSimulationData)
	return err
}
