// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api_types

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// Defines values for WowCharacterRealm.
const (
	Draenor    WowCharacterRealm = "draenor"
	Hydraxis   WowCharacterRealm = "hydraxis"
	Silvermoon WowCharacterRealm = "silvermoon"
	Thrall     WowCharacterRealm = "thrall"
)

// Defines values for WowCharacterRegion.
const (
	Cn WowCharacterRegion = "cn"
	Eu WowCharacterRegion = "eu"
	Kr WowCharacterRegion = "kr"
	Tw WowCharacterRegion = "tw"
	Us WowCharacterRegion = "us"
)

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

// Simulation All details & data about a simulation.
type Simulation struct {
	// Content The output / result of the simulation operation
	Content *string `json:"content,omitempty"`

	// Id ID for the simulation operation
	Id     *string           `json:"id,omitempty"`
	Status *SimulationStatus `json:"status,omitempty"`
}

// SimulationStatus defines model for Simulation.Status.
type SimulationStatus string

// SimulationOptions Specifices sim options, and the character of interest to sim, send this to the api
type SimulationOptions struct {
	// WowCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us)
	WowCharacter WowCharacter `json:"wow_character"`
}

// WowCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us)
type WowCharacter struct {
	// CharacterName The name of the WoW character
	CharacterName string `json:"character_name"`

	// Realm The realm which the character is located on
	Realm WowCharacterRealm `json:"realm"`

	// Region Identifies the region in which the characters realm is located
	Region WowCharacterRegion `json:"region"`
}

// WowCharacterRealm The realm which the character is located on
type WowCharacterRealm string

// WowCharacterRegion Identifies the region in which the characters realm is located
type WowCharacterRegion string

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
