// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api_types

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// Defines values for WowRealm.
const (
	Draenor    WowRealm = "draenor"
	Hydraxis   WowRealm = "hydraxis"
	Silvermoon WowRealm = "silvermoon"
	Thrall     WowRealm = "thrall"
)

// Defines values for WowRegion.
const (
	Cn WowRegion = "cn"
	Eu WowRegion = "eu"
	Kr WowRegion = "kr"
	Tw WowRegion = "tw"
	Us WowRegion = "us"
)

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

// Simulation All details & data about a simulation.
type Simulation struct {
	// ErrorText Error message for the simulation job (if one occurred)
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation
	Id *string `json:"id,omitempty"`

	// SimResult The raw output / result of the simulation operation
	SimResult        *string           `json:"sim_result,omitempty"`
	SimulationStatus *SimulationStatus `json:"simulation_status,omitempty"`
}

// SimulationOptions Specifices sim options, and the character of interest to sim, send this to the api
type SimulationOptions struct {
	// WowCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us)
	WowCharacter WowCharacter `json:"wow_character"`
}

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// WowCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us)
type WowCharacter struct {
	// CharacterName The name of the WoW character
	CharacterName string `json:"character_name"`

	// Realm The realm which the character is located on
	Realm WowRealm `json:"realm"`

	// Region Identifies the region in which the characters realm is located
	Region WowRegion `json:"region"`
}

// WowRealm The realm which the character is located on
type WowRealm string

// WowRegion Identifies the region in which the characters realm is located
type WowRegion string

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
