/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/simulation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description View the result of a simulation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the simulation to query */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The simulation result, or, if the simulation is currently in progress, the current state of the simulation job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["simulation"];
                    };
                };
                404: components["responses"]["not_found_error"];
                500: components["responses"]["internal_error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request a simulation, powered by SimC. */
        post: operations["simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us) */
        wow_character: {
            /**
             * @description Identifies the region in which the characters realm is located
             * @example us
             * @enum {string}
             */
            region: "us" | "eu" | "kr" | "tw" | "cn";
            /**
             * @description The realm which the character is located on
             * @example hydraxis
             * @enum {string}
             */
            realm: "thrall" | "hydraxis" | "silvermoon" | "draenor";
            /**
             * @description The name of the WoW character
             * @example John
             */
            character_name: string;
        };
        /** @description Specifices sim options, and the character of interest to sim, send this to the api */
        simulation_options: {
            wow_character: components["schemas"]["wow_character"];
        };
        /** @description All details & data about a simulation. */
        simulation: {
            /**
             * @description ID for the simulation operation
             * @example 41e9a22f-d2c1-48b2-b234-15db461049d4
             */
            id?: string;
            simulation_status?: components["schemas"]["simulation_status"];
            /**
             * @description The raw output / result of the simulation operation
             * @example ...
             */
            sim_result?: string;
            /** @description Error message for the simulation job (if one occurred) */
            error_text?: string;
        };
        /** @enum {string} */
        simulation_status: "in_progress" | "in_queue" | "error" | "complete";
        /** @description Error response returned by API when something goes wrong */
        error_response: {
            /** @description Message explaining the error */
            message?: string;
        };
    };
    responses: {
        /** @description Returned when the request is malformed or contains invalid input. */
        bad_request_error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["error_response"];
            };
        };
        /** @description Returned when the api could not locate a requested resource. */
        not_found_error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["error_response"];
            };
        };
        /** @description Returned whenever an internal server error occurs. This usually means the cause for the error was out of the control of the caller. */
        internal_error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["error_response"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Specify simulation options and wow characters here. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["simulation_options"];
            };
        };
        responses: {
            /** @description Simulation request was accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description ID of the simulation that was created */
                        simulation_id?: string;
                    };
                };
            };
            /** @description When one or more of the simulation options were invalid. For example, passing an invalid region or realm for the wow character may cause this. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["error_response"];
                };
            };
            404: components["responses"]["not_found_error"];
            500: components["responses"]["internal_error"];
        };
    };
}
