# https://docs.docker.com/reference/compose-file/

version: "3.9"

services:
  discord_bot:
    build:
      context: ./apps/discord_bot
      # We are using multiple build contexts so we can easily copy the modules in /pkg/ into the containers
      # https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/
      additional_contexts:
        root: ./
        pkg: ./pkg
      tags:
        - "saint_sim_discord_bot:latest"
    networks:
      - saint_network
    depends_on:
      - api
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
  api:
    build:
      context: ./apps/api
      additional_contexts:
        root: ./
        pkg: ./pkg
      tags:
        - "saint_sim_api:latest"
    # Expose port 8080 in container to host machine on port 8000
    #* this is just for development
    ports:
      - 8000:8080
    networks:
      - saint_network
    depends_on:
      - saint_postgres

  # https://www.postgresql.org/docs/14/libpq-envars.html
  saint_postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - saint_network
    restart: always # this policy always restarts the container until its removal.

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - saint_postgres
    restart: always

# shared network to allow the containers to communicate
networks:
  saint_network:
