/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulateIndexRouteImport } from './routes/simulate/index'
import { Route as SimulationSimulationIdRouteImport } from './routes/simulation/$simulationId'
import { Route as SimulateTopGearRouteImport } from './routes/simulate/top-gear'
import { Route as SimulateBasicRouteImport } from './routes/simulate/basic'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateIndexRoute = SimulateIndexRouteImport.update({
  id: '/simulate/',
  path: '/simulate/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationSimulationIdRoute = SimulationSimulationIdRouteImport.update({
  id: '/simulation/$simulationId',
  path: '/simulation/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateTopGearRoute = SimulateTopGearRouteImport.update({
  id: '/simulate/top-gear',
  path: '/simulate/top-gear',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateBasicRoute = SimulateBasicRouteImport.update({
  id: '/simulate/basic',
  path: '/simulate/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRoute
  '/simulate/basic': typeof SimulateBasicRoute
  '/simulate/top-gear': typeof SimulateTopGearRoute
  '/simulation/$simulationId': typeof SimulationSimulationIdRoute
  '/simulate/': typeof SimulateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRoute
  '/simulate/basic': typeof SimulateBasicRoute
  '/simulate/top-gear': typeof SimulateTopGearRoute
  '/simulation/$simulationId': typeof SimulationSimulationIdRoute
  '/simulate': typeof SimulateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRoute
  '/simulate/basic': typeof SimulateBasicRoute
  '/simulate/top-gear': typeof SimulateTopGearRoute
  '/simulation/$simulationId': typeof SimulationSimulationIdRoute
  '/simulate/': typeof SimulateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/simulate/basic'
    | '/simulate/top-gear'
    | '/simulation/$simulationId'
    | '/simulate/'
    | '/api/auth/$'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/simulate/basic'
    | '/simulate/top-gear'
    | '/simulation/$simulationId'
    | '/simulate'
    | '/api/auth/$'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/account'
    | '/simulate/basic'
    | '/simulate/top-gear'
    | '/simulation/$simulationId'
    | '/simulate/'
    | '/api/auth/$'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SimulateBasicRoute: typeof SimulateBasicRoute
  SimulateTopGearRoute: typeof SimulateTopGearRoute
  SimulationSimulationIdRoute: typeof SimulationSimulationIdRoute
  SimulateIndexRoute: typeof SimulateIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate/': {
      id: '/simulate/'
      path: '/simulate'
      fullPath: '/simulate/'
      preLoaderRoute: typeof SimulateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$simulationId': {
      id: '/simulation/$simulationId'
      path: '/simulation/$simulationId'
      fullPath: '/simulation/$simulationId'
      preLoaderRoute: typeof SimulationSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate/top-gear': {
      id: '/simulate/top-gear'
      path: '/simulate/top-gear'
      fullPath: '/simulate/top-gear'
      preLoaderRoute: typeof SimulateTopGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate/basic': {
      id: '/simulate/basic'
      path: '/simulate/basic'
      fullPath: '/simulate/basic'
      preLoaderRoute: typeof SimulateBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SimulateBasicRoute: SimulateBasicRoute,
  SimulateTopGearRoute: SimulateTopGearRoute,
  SimulationSimulationIdRoute: SimulationSimulationIdRoute,
  SimulateIndexRoute: SimulateIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
