// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CharacterClass.
const (
	Deathknight CharacterClass = "deathknight"
	Demonhunter CharacterClass = "demonhunter"
	Druid       CharacterClass = "druid"
	Evoker      CharacterClass = "evoker"
	Hunter      CharacterClass = "hunter"
	Mage        CharacterClass = "mage"
	Monk        CharacterClass = "monk"
	Paladin     CharacterClass = "paladin"
	Priest      CharacterClass = "priest"
	Rogue       CharacterClass = "rogue"
	Shaman      CharacterClass = "shaman"
	Warlock     CharacterClass = "warlock"
	Warrior     CharacterClass = "warrior"
)

// Defines values for EquipmentSlot.
const (
	Back     EquipmentSlot = "back"
	Chest    EquipmentSlot = "chest"
	Feet     EquipmentSlot = "feet"
	Finger1  EquipmentSlot = "finger1"
	Finger2  EquipmentSlot = "finger2"
	Hands    EquipmentSlot = "hands"
	Head     EquipmentSlot = "head"
	Legs     EquipmentSlot = "legs"
	MainHand EquipmentSlot = "main_hand"
	Neck     EquipmentSlot = "neck"
	OffHand  EquipmentSlot = "off_hand"
	Shirt    EquipmentSlot = "shirt"
	Shoulder EquipmentSlot = "shoulder"
	Tabard   EquipmentSlot = "tabard"
	Trinket1 EquipmentSlot = "trinket1"
	Trinket2 EquipmentSlot = "trinket2"
	Waist    EquipmentSlot = "waist"
	Wrist    EquipmentSlot = "wrist"
)

// Defines values for EquipmentSource.
const (
	Bag      EquipmentSource = "bag"
	Equipped EquipmentSource = "equipped"
)

// Defines values for FightStyle.
const (
	CastingPatchwerk FightStyle = "CastingPatchwerk"
	CleaveAdd        FightStyle = "CleaveAdd"
	DungeonSlice     FightStyle = "DungeonSlice"
	ExecutePatchwerk FightStyle = "ExecutePatchwerk"
	HeavyMovement    FightStyle = "HeavyMovement"
	HecticAddCleave  FightStyle = "HecticAddCleave"
	LightMovement    FightStyle = "LightMovement"
	Patchwerk        FightStyle = "Patchwerk"
	TargetDummy      FightStyle = "TargetDummy"
)

// Defines values for SimulationConfigBasicKind.
const (
	SimulationConfigBasicKindBasic SimulationConfigBasicKind = "basic"
)

// Defines values for SimulationConfigTopGearKind.
const (
	SimulationConfigTopGearKindTopGear SimulationConfigTopGearKind = "topGear"
)

// Defines values for SimulationKind.
const (
	SimulationKindBasic   SimulationKind = "basic"
	SimulationKindTopGear SimulationKind = "topGear"
)

// Defines values for SimulationResultBasicKind.
const (
	Basic SimulationResultBasicKind = "basic"
)

// Defines values for SimulationResultTopGearKind.
const (
	SimulationResultTopGearKindTopGear SimulationResultTopGearKind = "topGear"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// CharacterClass defines model for character_class.
type CharacterClass string

// CharacterEquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
type CharacterEquippedItems struct {
	Back     EquipmentItem  `json:"back"`
	Chest    EquipmentItem  `json:"chest"`
	Feet     EquipmentItem  `json:"feet"`
	Finger1  EquipmentItem  `json:"finger1"`
	Finger2  EquipmentItem  `json:"finger2"`
	Hands    EquipmentItem  `json:"hands"`
	Head     EquipmentItem  `json:"head"`
	Legs     EquipmentItem  `json:"legs"`
	MainHand EquipmentItem  `json:"main_hand"`
	Neck     EquipmentItem  `json:"neck"`
	OffHand  *EquipmentItem `json:"off_hand,omitempty"`
	Shoulder EquipmentItem  `json:"shoulder"`
	Trinket1 EquipmentItem  `json:"trinket1"`
	Trinket2 EquipmentItem  `json:"trinket2"`
	Waist    EquipmentItem  `json:"waist"`
	Wrist    EquipmentItem  `json:"wrist"`
}

// CharacterSlotHighWatermark The character's current and highest unlocked upgrade track item levels for a specific gear slot from Additional Character Info.
type CharacterSlotHighWatermark struct {
	CurrentItemLevel int           `json:"current_item_level"`
	MaxItemLevel     int           `json:"max_item_level"`
	Slot             EquipmentSlot `json:"slot"`
}

// CharacterTalentLoadout A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
type CharacterTalentLoadout struct {
	// Name The name of the talent loadout.
	Name *string `json:"name,omitempty"`

	// Talents The WoW talent string
	Talents string `json:"talents"`
}

// EquipmentItem defines model for equipment_item.
type EquipmentItem struct {
	BonusIds        *[]int          `json:"bonus_ids,omitempty"`
	CraftedStats    *[]int          `json:"crafted_stats,omitempty"`
	CraftingQuality *int            `json:"crafting_quality"`
	DisplayName     string          `json:"display_name"`
	EnchantId       *int            `json:"enchant_id"`
	GemIds          *[]int          `json:"gem_ids,omitempty"`
	ItemId          int             `json:"item_id"`
	ItemLevel       *int            `json:"item_level"`
	Name            string          `json:"name"`
	RawLine         string          `json:"raw_line"`
	Slot            EquipmentSlot   `json:"slot"`
	Source          EquipmentSource `json:"source"`
}

// EquipmentSlot defines model for equipment_slot.
type EquipmentSlot string

// EquipmentSource defines model for equipment_source.
type EquipmentSource string

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Code Error code
	Code string `json:"code"`

	// Message Message explaining the error
	Message string `json:"message"`
}

// FightStyle Simc fight style. For up-to-date list of supported fight styles, check the simc repo:
//
//	https://github.com/simulationcraft/simc/blob/5e3d3bcf9d6437c82330ff3826041df164b535a1/engine/util/util.cpp#L566
type FightStyle string

// HealthResponse defines model for health_response.
type HealthResponse struct {
	Status string `json:"status"`
}

// Simulation Polling envelope for a simulation job.
type Simulation struct {
	// ErrorText Populated when status = error.
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation.
	Id openapi_types.UUID `json:"id"`

	// Kind The concrete kind of simulation to perform (basic, topGear, etc.)
	Kind SimulationKind `json:"kind"`

	// RawSimcInput The raw SIMC input for the sim
	RawSimcInput *string `json:"raw_simc_input,omitempty"`

	// Result Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
	Result *SimulationResult `json:"result,omitempty"`
	Status SimulationStatus  `json:"status"`
}

// SimulationConfigBasic Specifies simulation options to send to the API.
type SimulationConfigBasic struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig      `json:"core_config"`
	Kind       SimulationConfigBasicKind `json:"kind"`
}

// SimulationConfigBasicKind defines model for SimulationConfigBasic.Kind.
type SimulationConfigBasicKind string

// SimulationConfigTopGear Top gear simulation options. The gear which we should try to find some optimal combination of.
type SimulationConfigTopGear struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig `json:"core_config"`

	// Equipment The gear to consider in the simulation. We will try to find optimal combinations of these. Must have at least 1 item per slot so it is possible to form a full equipment set.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationConfigTopGearKind `json:"kind"`
}

// SimulationConfigTopGearKind defines model for SimulationConfigTopGear.Kind.
type SimulationConfigTopGearKind string

// SimulationCoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
type SimulationCoreConfig struct {
	// FightStyle Simc fight style. For up-to-date list of supported fight styles, check the simc repo:
	//  https://github.com/simulationcraft/simc/blob/5e3d3bcf9d6437c82330ff3826041df164b535a1/engine/util/util.cpp#L566
	FightStyle *FightStyle `json:"fight_style,omitempty"`
}

// SimulationKind The concrete kind of simulation to perform (basic, topGear, etc.)
type SimulationKind string

// SimulationOptions defines model for simulation_options.
type SimulationOptions struct {
	union json.RawMessage
}

// SimulationResult Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
type SimulationResult struct {
	union json.RawMessage
}

// SimulationResultBasic Result of a `basic` simulation — a single actor simmed with their equipped gear. For now this just surfaces the headline DPS and the raw simc log; it will grow structured stats later.
type SimulationResultBasic struct {
	// Dps Mean DPS of the simmed actor.
	Dps  float64                   `json:"dps"`
	Kind SimulationResultBasicKind `json:"kind"`

	// RawLog Human-readable stdout from simc. Optional; may be truncated or omitted for large runs.
	RawLog *string `json:"raw_log,omitempty"`
}

// SimulationResultBasicKind defines model for SimulationResultBasic.Kind.
type SimulationResultBasicKind string

// SimulationResultTopGear Result of a `topGear` simulation.
// To keep payload size bounded when many profilesets are generated, items are sent once in `equipment` and each profileset references them by index. A profileset's `head: 3` means "the item at equipment[3]". Indices are stable for the lifetime of this result object; they are NOT indices into the request's equipment array (the worker may have reordered/deduplicated).
type SimulationResultTopGear struct {
	// Equipment Item table for this result. Every integer slot value inside `profilesets[*].items` is an index into this array.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationResultTopGearKind `json:"kind"`

	// Metric The statistic `mean` on each profileset refers to. Copied from simc's `sim.profilesets.metric` — usually "dps".
	Metric string `json:"metric"`

	// Profilesets All simmed loadouts, sorted by `mean` descending (best first).
	Profilesets []TopGearProfilesetResult `json:"profilesets"`
}

// SimulationResultTopGearKind defines model for SimulationResultTopGear.Kind.
type SimulationResultTopGearKind string

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// TopGearProfilesetItems Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
type TopGearProfilesetItems struct {
	Back     int `json:"back"`
	Chest    int `json:"chest"`
	Feet     int `json:"feet"`
	Finger1  int `json:"finger1"`
	Finger2  int `json:"finger2"`
	Hands    int `json:"hands"`
	Head     int `json:"head"`
	Legs     int `json:"legs"`
	MainHand int `json:"main_hand"`
	Neck     int `json:"neck"`

	// OffHand Absent when this loadout has no off-hand (two-hander).
	OffHand  *int `json:"off_hand,omitempty"`
	Shoulder int  `json:"shoulder"`
	Trinket1 int  `json:"trinket1"`
	Trinket2 int  `json:"trinket2"`
	Waist    int  `json:"waist"`
	Wrist    int  `json:"wrist"`
}

// TopGearProfilesetResult One simmed loadout and its headline metric.
type TopGearProfilesetResult struct {
	// Items Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
	Items TopGearProfilesetItems `json:"items"`

	// Mean Mean of `metric` (typically DPS) for this loadout.
	Mean float64 `json:"mean"`

	// MeanError simc's reported error bound on `mean`.
	MeanError *float64 `json:"mean_error,omitempty"`

	// Name Profileset label as generated by the worker (e.g. "Combo7"). Matches `sim.profilesets.results[].name` in the raw simc json2 blob, which is how the worker joins metrics to loadouts.
	Name string `json:"name"`
}

// WowCharacter The representation of a wow character.
type WowCharacter struct {
	// ActiveTalents A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
	ActiveTalents CharacterTalentLoadout `json:"active_talents"`

	// BagItems Items in the character's bags
	BagItems *[]EquipmentItem `json:"bag_items,omitempty"`

	// CatalystCurrencies Catalyst charges
	CatalystCurrencies *[]struct {
		// Id The id of the currency
		Id int `json:"id"`

		// Quantity The quantity of the currency the character has
		Quantity int `json:"quantity"`
	} `json:"catalyst_currencies,omitempty"`
	CharacterClass CharacterClass `json:"character_class"`

	// EquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
	EquippedItems CharacterEquippedItems `json:"equipped_items"`
	Level         int                    `json:"level"`

	// LootSpec The loot specialization of your character.
	LootSpec *string `json:"loot_spec,omitempty"`

	// Name Name of the character
	Name               *string                       `json:"name,omitempty"`
	Professions        *string                       `json:"professions"`
	Race               string                        `json:"race"`
	Region             *string                       `json:"region"`
	Role               *string                       `json:"role"`
	Server             *string                       `json:"server"`
	SlotHighWatermarks *[]CharacterSlotHighWatermark `json:"slot_high_watermarks,omitempty"`
	Spec               string                        `json:"spec"`

	// TalentLoadouts The talent loadouts that were not active
	TalentLoadouts      *[]CharacterTalentLoadout `json:"talent_loadouts,omitempty"`
	UpgradeAchievements *[]int                    `json:"upgrade_achievements,omitempty"`
}

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// MalformedRequest Error response returned by API when something goes wrong
type MalformedRequest = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions

// AsSimulationConfigBasic returns the union data inside the SimulationOptions as a SimulationConfigBasic
func (t SimulationOptions) AsSimulationConfigBasic() (SimulationConfigBasic, error) {
	var body SimulationConfigBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigBasic overwrites any union data inside the SimulationOptions as the provided SimulationConfigBasic
func (t *SimulationOptions) FromSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigBasic performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigBasic
func (t *SimulationOptions) MergeSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationConfigTopGear returns the union data inside the SimulationOptions as a SimulationConfigTopGear
func (t SimulationOptions) AsSimulationConfigTopGear() (SimulationConfigTopGear, error) {
	var body SimulationConfigTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigTopGear overwrites any union data inside the SimulationOptions as the provided SimulationConfigTopGear
func (t *SimulationOptions) FromSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigTopGear performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigTopGear
func (t *SimulationOptions) MergeSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationOptions) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationOptions) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationConfigBasic()
	case "topGear":
		return t.AsSimulationConfigTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationOptions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationOptions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSimulationResultBasic returns the union data inside the SimulationResult as a SimulationResultBasic
func (t SimulationResult) AsSimulationResultBasic() (SimulationResultBasic, error) {
	var body SimulationResultBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultBasic overwrites any union data inside the SimulationResult as the provided SimulationResultBasic
func (t *SimulationResult) FromSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultBasic performs a merge with any union data inside the SimulationResult, using the provided SimulationResultBasic
func (t *SimulationResult) MergeSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationResultTopGear returns the union data inside the SimulationResult as a SimulationResultTopGear
func (t SimulationResult) AsSimulationResultTopGear() (SimulationResultTopGear, error) {
	var body SimulationResultTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultTopGear overwrites any union data inside the SimulationResult as the provided SimulationResultTopGear
func (t *SimulationResult) FromSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultTopGear performs a merge with any union data inside the SimulationResult, using the provided SimulationResultTopGear
func (t *SimulationResult) MergeSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationResultBasic()
	case "topGear":
		return t.AsSimulationResultTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	Health(c *gin.Context)

	// (POST /simulation)
	Simulate(c *gin.Context)

	// (GET /simulation/{id})
	GetSimulation(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// Simulate operation middleware
func (siw *ServerInterfaceWrapper) Simulate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Simulate(c)
}

// GetSimulation operation middleware
func (siw *ServerInterfaceWrapper) GetSimulation(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSimulation(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.Health)
	router.POST(options.BaseURL+"/simulation", wrapper.Simulate)
	router.GET(options.BaseURL+"/simulation/:id", wrapper.GetSimulation)
}

type BadRequestErrorJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type MalformedRequestJSONResponse ErrorResponse

type NotFoundErrorJSONResponse ErrorResponse

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse HealthResponse

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimulateRequestObject struct {
	Body *SimulateJSONRequestBody
}

type SimulateResponseObject interface {
	VisitSimulateResponse(w http.ResponseWriter) error
}

type Simulate202JSONResponse struct {
	// SimulationId ID of the simulation that was created
	SimulationId *string `json:"simulation_id,omitempty"`
}

func (response Simulate202JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type Simulate400JSONResponse ErrorResponse

func (response Simulate400JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Simulate401JSONResponse ErrorResponse

func (response Simulate401JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Simulate404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response Simulate404JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type Simulate422JSONResponse struct{ MalformedRequestJSONResponse }

func (response Simulate422JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type Simulate500JSONResponse struct{ InternalErrorJSONResponse }

func (response Simulate500JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulationRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSimulationResponseObject interface {
	VisitGetSimulationResponse(w http.ResponseWriter) error
}

type GetSimulation200JSONResponse Simulation

func (response GetSimulation200JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response GetSimulation404JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSimulation500JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (POST /simulation)
	Simulate(ctx context.Context, request SimulateRequestObject) (SimulateResponseObject, error)

	// (GET /simulation/{id})
	GetSimulation(ctx context.Context, request GetSimulationRequestObject) (GetSimulationResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *gin.Context) {
	var request HealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Simulate operation middleware
func (sh *strictHandler) Simulate(ctx *gin.Context) {
	var request SimulateRequestObject

	var body SimulateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Simulate(ctx, request.(SimulateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Simulate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SimulateResponseObject); ok {
		if err := validResponse.VisitSimulateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSimulation operation middleware
func (sh *strictHandler) GetSimulation(ctx *gin.Context, id openapi_types.UUID) {
	var request GetSimulationRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSimulation(ctx, request.(GetSimulationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSimulation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSimulationResponseObject); ok {
		if err := validResponse.VisitGetSimulationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Rb/W7cRpJ/lQL3gNgHavRpb6Lg/lAcb6LdOBEi5YyDJYyaZM2wLbKb7m5qzA0E3EPc",
	"E96THKq6yeEMOZqRLtnN5o9YQ/ZHVfWv65u/RqkuK61QORud/hoZtJVWFvlHIrKpwU81WjdFY7Shh6lW",
	"DpWjP0VVFTIVTmq1/9FqRc9smmMp6K9/MziLTqM/7S932Pdv7T6vNm03ix4eHuIoQ5saWdFq0Wn0M7ra",
	"KMxgkaMClyMESkBaKEUx06bEDLQBIkhIZUGqe1HIDKSqajeJHuJIKodGieKfSz3eowGhoKUGLBp6xMuA",
	"TtPa2Alc5dJCbWtRFA2UKJRlrlNRW4SZNvzLT1kIC7p2oGd+iFbO6KL7KYoCDfPfyak9xn+gCN4yqe0I",
	"MK1EkgbOLs79sdYWjT8umAlZYAYWS6GcTIGPkikjRpR205muVfYHwKGoJKS6LjJQ2kGhU+EQRAtPzIhn",
	"XZsUJxEtF7ZiknNhROrQTNNCWH6Eqi6j0w/RQhgjtYniKK8JJlEclVrdRXFUiUJkUkVxZPS8xiiObC5K",
	"QQ9KMaffC2EKndLYzNQyo39RuPxOyXnuaAUj6ejpcalVtz7e6zs00U0cuabC6DSyzkg1J3EvCcVPtawq",
	"zKbSYckUr4rnnB6Dy4Xz2GsnQlobg8oVDeTCQrtMDHfYeBDwoxKVA1toN4FbPZtNc6GyW7rhupTO9aW+",
	"XLm2aEGAW+g9Gk6DUFRaTa4VM6srNE62Giy924qBlhDm0bMfrsrTps0QnzNLqjmaw+dOPHr6RJKafcY0",
	"FNnTZxU4f8ZepZCKwfD0qQqfc+Qt+J4+0+akC9A8fSZdtzt0h8+e+YyzXwj5HGgvzDOmPcQRKUVpMCMV",
	"x/gJ59MTW+wvaXvr2r1amLYkBySFW7a8Nst70BNoT0J9LC1VnU4+YupWVR2poWku5/l0IRyaUpi7ob67",
	"6quiL2yr5kCoDGguOSi1InWMGdTV3IgMwRmR3gEJBQq8x8KyPRdgK0zlTKYwR2FYDcLM6BLOskzSfqKA",
	"N53aO1czPRkouLA/S3zKi9PTwCU5HHM0/kJ93jqGCNj9jHn0+hnzw3iMqgEJjx+GEwUtUGiR6doNz+EM",
	"rLjHDPw4COPAm7AYKkEUwUK6nK2HEiW2/lEYO4H/0jWkQgF+rrQh+yWtlz+NupRlCiLLtIIX2kAplPfM",
	"/ADe1UKJqgapYC5KfDk8HNp1HEJ9elZZoFUG9jjsN77We/2+XSPMGKywdkrtcmNHsHaJT39dt6ha1XYq",
	"vQHpnIIhmMITYYxo+GiNmDnMptYJ96y5Us2nn2pRSNewbOuiEEmB0akzNcYjq2TSVoVopu0pDKSKKs0F",
	"MZrttuAcy2cwzpD3WwwHr17J7SRs5MWIxbSQavzlcy52HHkn9gnz/PgNKoEpXzuUpXC63XqcPI7OlqfW",
	"gf7nW5eeE0EESEMLOZEIk4062QPJ9bhp/WWmfz4+fTV0GaiGXeIvq0t0uVRzmGu0sDCatceaidHZxuX5",
	"3QhxJVpLwclg2jv/gnRuIaSirbu4dqvealeNPU1jAJlRzDO1rilGNmedziOAR0zgL9pAXe05vZdRFFdI",
	"y1G1rSsyCZj1R9sY0hzTOybY0lIGK316rSB3rrKn+/tz6fI6maS63LeyrAuOSFl50e90Pyl0sv8Kj7Pj",
	"JJ19lb0+Of5z+uXR8fHBbHb85dHrg5PDbHb4+iR5dfxKHO6jmkuF+7WTBf9vklbVn3549fo1xzktUi6E",
	"S/MFGsL4t7Wao1aXheSbdCXMHN23dVk2URy9/Yxp7bA//ntMnUzPsuxNgeKepvxA7L7T90i45BHivun9",
	"fiMsKeL+In7uWTYO8hxF4fIVmK6ii+xB7UPhz6Ks6NjCpGYrHsLcMRws5T+EwYUuCgIeqnssdIWtN9ZN",
	"gY86GVpzf+EcfnZjS1Y0tw1YPWHwHx7XoybdW4S1YPrbLtHTI4Zo4L9onaWQTg7xK3F0NNvLjtLDvZMv",
	"k6O95Oj4ZO/wVZacvD48OPkqOyH9pU0pXHQa1T41MCDkTm6PepbUTHl4MDgE6imnb8Y9EyMWcHn+7k2b",
	"4lnyNkaIQVsX7gmkhAl02h2IdpwaJqwDiiXEHMa7gWuaajWT82kirExHFI538NGunif9Y8FpsKgy+pek",
	"cnZxPuLetw7xNt4WejFdDiafSRsM1D1BLv1ZPWy0ysazebPtXgYJLulZJWc3kTpdfYfCjCBLVyFgGsh0",
	"AgQ7frnIZZrDAsG7AuBMQ5KeSZWx2eMppSgg1WUiVVhm9oc7gs5LGL9izKvTkGplZcbZ1DX9MYH3CAtZ",
	"FCsiGOHehoDE4gTe1dZBLu4RhIMChXVw6APYCkOkajVITsZX2lqZFMhra1OCgFldFP0EH3JY0znNT0x2",
	"rDnU66BsgbIVln3J9gUbDwG7FaIrJ7t6LG+0Cf6BH+Gzo9KCzQUFpQm6BaICURR9CBMNFl7wFYvBBZDH",
	"gC6dvBygcs3PeUyi/aEPD48z1sp2JOlBngw6ZDrZR1qS7jTBgs++R/93K+SvqpD4kVNbIShcbKZJEk0l",
	"oVWbLUSuybVHIbvsVUU7cX6Y9fYOl7Kn5pfE7zyxnfDQnWPzI4dyUWtPtcKfZtHphyfoiR5JD/FT53UU",
	"bYH60iqvibupMANdu8oXogSpkqpA8oH6yofLWtLXsu5FUSP/tdDmDg0sjHTIlvC2N8fKMmx726qzTFAg",
	"ZZHzbMFahpDGwj2aRDhZft29ySiaUdqBQaKqdki6SiswKDJfJxig6Rmo8EQ+AxVh4u+AihWSnoCKdYpu",
	"xlCwyc35md96FNzymNv+Dfzf//4fdq/VvEAQqdNsustefk6arkLEWs8HZkovfFLuI1kjW5uZSNEjiaL9",
	"QiqEby8uO0yQu8l6t9Dzr+nA2erNjV6AdaZOXU3qlxNQQM66GasYZZUdi1qF4q1Cyi6Qz7xM+k52puuk",
	"6EXEqi4T7wzs6kqFBIgeMSzf16VQewRhQebWOk55ckKS2J7AT5XPGn8NpWggQXCmVimHJdp0JTVywwsK",
	"DcHUynoZ7OTPkWh20habfbcVpIRRfaxMrtWVhjvECirRFFqQMvk7QqJrX+mj6KoUqoHK6Jks0KKzIAw5",
	"QorCJMxi9lP8Q0veh1Ypkh657Sz+LUMGRZr3lgGDMzSoAsRKSBqQKsPPEzjrDfvCwi2h7xSOb0OZ/joi",
	"TLB3JNzS7flwfHMdTeBcZZLWZHocn1wbCBVyhk62mWBpwQTxsGhZnTU878efrogWXkeqEDCEgvMXtudp",
	"sZMEL3oqlpDAjpxBbTI0mO1nmNW+YI7Zy7E78IjPeU5c9rnoqJ7A23s0DYRspXcSvcaX7JvCbe/MPvz7",
	"zYTPiau93ByR4eeWOXpEnHji/uF+YxyV6MyYpiMngxSItE6mcEvnf0t2ZRRLZNgm8EZXkm5de00JQFaW",
	"k54wJn67W9aUbQvINd2368iLYBn20yUcIbi32kixxHuapLJClcHGYH2CK2laNmgOqkyqObxI0DqYSWPd",
	"yyecQZDodElML0ZfPY5xDRPEvuqc91nbon56yaRwyFIRNXODlsQm1fRTjdxE0WYcW69lFAYjDG3og7hA",
	"s8eI70c9BaZsANv8EhvArvzkr0u4IcM7gFAJLi16ERJs+gqMr8e2pom2LPaclolh8aFrixi+alsfRt4s",
	"2xs2vTwaf9m1KYy8Cq0Iwzdtu8FYBbTXUjBSWcFNbPdbA9buVcIGJohb2k7euSD3E/RsxvKGF53kzcte",
	"NrBfe+11EYzUlHqdAhvfbhBjV/EfeWU2vPqXqNxv1jaDg/pJ4ZoCZA9AOrv0JL3uGeZ/nqv5/Dy2JUJt",
	"cCn1jJSv1/0vXFPJlFX/txeXL5fmtVcY3sHPpN2WTXKrewbzYzAUN3w3IftWZMS8Hdhxn/Ha9sXSBBYi",
	"wQKEXXpmZGt6nskLnMwncB290WWi/3wdvZzAO+EIS0MD6Q/WfriZ0L5dWNh5/B+tVkeQFDqJQ+ZPWsg5",
	"fuj2+6ilsuGYOeZsbeEuLnCoV/JZttZwDJSrScDxrDhWBklxtDlHELDQi2VbyRCDInXyHqe9NoDHwLix",
	"i+KBq4mPt/LJtXa7Lywkgq/vb+SGpcKJorFu6ptE0jbuWs2hhUFMxxxXtl+7nhvyVTLr+mH9Ps2o3v1U",
	"C+VCS8Fwkfbt+lJrHYm5sCOLj9UWuu1GFdq6pIbtorsdux/eJo9Xujd3W2BtHtvV0KNQSiVL8q0Ox8RZ",
	"aO2mtsINrjO99l1PopB/7/Df6Nqswn/giY2rmx97bTT9asOoe4zWtqnEDY0W/Rg83dBngfNQU9y+hva5",
	"2a0DfTv4bkOHPWq7G6nHW91GANge5IZ+pFavbOhLWu1rCk3CCzTImTmv0nZVK4+ptHWqQ9fdVKS5RF+5",
	"flrPztrFbfvX1u/X4HoFgQX0xOtae3jl+ezT2kjXXBKjXqOdVfJv2JzVLh8pKLI8yJ/31tTU3HGeFpL7",
	"0VjEonY5Ksfxvc+w0fU6uzifXKtfrM+/3p5Vcu9v2JzCdX1wcJyKSk7vsOEfeMtOEXJdqb9YiASVr9B7",
	"D9Dfyygst7x6gpkg2X6DwqBp2Un4119a/+Kv76+i9Y77b9CRUqUZ8Nf3Vx2zHI7uVcK4JnzjYFc4ql2u",
	"TdAqp+C3Dex9XLitrF3pO1S2LRcmFJPZOgTI37y9unr78/Tsl6vvp7/8/IPPHxF+OJYiT+328uz8x6vp",
	"2cU5D/CiYvSSNDzXS+nkzlX+YwOpZnrs+kgbUtzcNyH7WSMrpHKQ1FYqtOQezmXqC5+ZtKk2GSTaxURi",
	"DJV2xKL/poTrUmjuQxqJF5vVrjYY+1QpSdX7nKEY7aTjpMMlb3l2cR7F0T0a66k8nBxMDjhCqlCJSkan",
	"0fHkYHLMHy24nMG873s56M85urGEoM/hE7N+aGieoO27zofzLDqNvvcrxavfKB0dHPxmX4OsN6uMfA5C",
	"dEobSG0mNOQhjvZX200qbUdZ9d8v9TtN6IRIJTLMLmX5Zsj2pR/MrXF+hW901vxmPI/U2kbY9o0MzVgb",
	"Q44GJ1FfZZLtehgc09GTSF5rEloSuaFvZpmY74qSbG6EhdQgRR+jLv66Qh4yvlyw/f6M1hRpihUt+hBH",
	"J78hAn/X7+JG+iU8/Yd/CPq7op1UaVFn6D8B66tpojw1mHmV1lJ/somoDoD765+P0byjo+3zht/PPcTR",
	"K3/ej89c+/Kwb+q5nNe3ih9uHuJVs//h5uFmTa/s/yqzh41q9D8lLoIwlwWWXllloFW+Q7eENitsI0p0",
	"aCyTN/Tmxu+Yhk81mqZ1C0jtL50CjnhW1ULcw9GWzrSHm99R0/f09QhGr1a59DKNQZsY5EAG0va+dZMK",
	"2nRz3IsYHRs1HJEgdxr+P2D8PDDSf/8XAAD//wEYf7T6OwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
