// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CharacterClass.
const (
	Deathknight CharacterClass = "deathknight"
	Demonhunter CharacterClass = "demonhunter"
	Druid       CharacterClass = "druid"
	Evoker      CharacterClass = "evoker"
	Hunter      CharacterClass = "hunter"
	Mage        CharacterClass = "mage"
	Monk        CharacterClass = "monk"
	Paladin     CharacterClass = "paladin"
	Priest      CharacterClass = "priest"
	Rogue       CharacterClass = "rogue"
	Shaman      CharacterClass = "shaman"
	Warlock     CharacterClass = "warlock"
	Warrior     CharacterClass = "warrior"
)

// Defines values for EquipmentSlot.
const (
	Back     EquipmentSlot = "back"
	Chest    EquipmentSlot = "chest"
	Feet     EquipmentSlot = "feet"
	Finger1  EquipmentSlot = "finger1"
	Finger2  EquipmentSlot = "finger2"
	Hands    EquipmentSlot = "hands"
	Head     EquipmentSlot = "head"
	Legs     EquipmentSlot = "legs"
	MainHand EquipmentSlot = "main_hand"
	Neck     EquipmentSlot = "neck"
	OffHand  EquipmentSlot = "off_hand"
	Shirt    EquipmentSlot = "shirt"
	Shoulder EquipmentSlot = "shoulder"
	Tabard   EquipmentSlot = "tabard"
	Trinket1 EquipmentSlot = "trinket1"
	Trinket2 EquipmentSlot = "trinket2"
	Waist    EquipmentSlot = "waist"
	Wrist    EquipmentSlot = "wrist"
)

// Defines values for EquipmentSource.
const (
	Bag      EquipmentSource = "bag"
	Equipped EquipmentSource = "equipped"
)

// Defines values for FightStyle.
const (
	CastingPatchwerk FightStyle = "casting_patchwerk"
	CleaveAdd        FightStyle = "cleave_add"
	DungeonSlice     FightStyle = "dungeon_slice"
	ExecutePatchwerk FightStyle = "execute_patchwerk"
	HeavyMovement    FightStyle = "heavy_movement"
	HecticAddCleave  FightStyle = "hectic_add_cleave"
	LightMovement    FightStyle = "light_movement"
	Patchwerk        FightStyle = "patchwerk"
	TargetDummy      FightStyle = "target_dummy"
)

// Defines values for SimulationConfigBasicKind.
const (
	SimulationConfigBasicKindBasic SimulationConfigBasicKind = "basic"
)

// Defines values for SimulationConfigTopGearKind.
const (
	SimulationConfigTopGearKindTopGear SimulationConfigTopGearKind = "topGear"
)

// Defines values for SimulationKind.
const (
	SimulationKindBasic   SimulationKind = "basic"
	SimulationKindTopGear SimulationKind = "topGear"
)

// Defines values for SimulationResultBasicKind.
const (
	Basic SimulationResultBasicKind = "basic"
)

// Defines values for SimulationResultTopGearKind.
const (
	SimulationResultTopGearKindTopGear SimulationResultTopGearKind = "topGear"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// CharacterClass defines model for character_class.
type CharacterClass string

// CharacterEquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
type CharacterEquippedItems struct {
	Back     EquipmentItem  `json:"back"`
	Chest    EquipmentItem  `json:"chest"`
	Feet     EquipmentItem  `json:"feet"`
	Finger1  EquipmentItem  `json:"finger1"`
	Finger2  EquipmentItem  `json:"finger2"`
	Hands    EquipmentItem  `json:"hands"`
	Head     EquipmentItem  `json:"head"`
	Legs     EquipmentItem  `json:"legs"`
	MainHand EquipmentItem  `json:"main_hand"`
	Neck     EquipmentItem  `json:"neck"`
	OffHand  *EquipmentItem `json:"off_hand,omitempty"`
	Shoulder EquipmentItem  `json:"shoulder"`
	Trinket1 EquipmentItem  `json:"trinket1"`
	Trinket2 EquipmentItem  `json:"trinket2"`
	Waist    EquipmentItem  `json:"waist"`
	Wrist    EquipmentItem  `json:"wrist"`
}

// CharacterSlotHighWatermark The character's current and highest unlocked upgrade track item levels for a specific gear slot from Additional Character Info.
type CharacterSlotHighWatermark struct {
	CurrentItemLevel int           `json:"current_item_level"`
	MaxItemLevel     int           `json:"max_item_level"`
	Slot             EquipmentSlot `json:"slot"`
}

// CharacterTalentLoadout A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
type CharacterTalentLoadout struct {
	// Name The name of the talent loadout.
	Name *string `json:"name,omitempty"`

	// Talents The WoW talent string
	Talents string `json:"talents"`
}

// EquipmentItem defines model for equipment_item.
type EquipmentItem struct {
	BonusIds        *[]int          `json:"bonus_ids,omitempty"`
	CraftedStats    *[]int          `json:"crafted_stats,omitempty"`
	CraftingQuality *int            `json:"crafting_quality"`
	DisplayName     string          `json:"display_name"`
	EnchantId       *int            `json:"enchant_id"`
	GemIds          *[]int          `json:"gem_ids,omitempty"`
	ItemId          int             `json:"item_id"`
	ItemLevel       *int            `json:"item_level"`
	Name            string          `json:"name"`
	RawLine         string          `json:"raw_line"`
	Slot            EquipmentSlot   `json:"slot"`
	Source          EquipmentSource `json:"source"`
}

// EquipmentSlot defines model for equipment_slot.
type EquipmentSlot string

// EquipmentSource defines model for equipment_source.
type EquipmentSource string

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Code Error code
	Code string `json:"code"`

	// Message Message explaining the error
	Message string `json:"message"`
}

// FightStyle Simc fight style
type FightStyle string

// HealthResponse defines model for health_response.
type HealthResponse struct {
	Status string `json:"status"`
}

// Simulation Polling envelope for a simulation job.
type Simulation struct {
	// ErrorText Populated when status = error.
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation.
	Id openapi_types.UUID `json:"id"`

	// Kind The concrete kind of simulation to perform (basic, topGear, etc.)
	Kind SimulationKind `json:"kind"`

	// Result Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
	Result *SimulationResult `json:"result,omitempty"`
	Status SimulationStatus  `json:"status"`
}

// SimulationConfigBasic Specifies simulation options to send to the API.
type SimulationConfigBasic struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig      `json:"core_config"`
	Kind       SimulationConfigBasicKind `json:"kind"`
}

// SimulationConfigBasicKind defines model for SimulationConfigBasic.Kind.
type SimulationConfigBasicKind string

// SimulationConfigTopGear Top gear simulation options. The gear which we should try to find some optimal combination of.
type SimulationConfigTopGear struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig `json:"core_config"`

	// Equipment The gear to consider in the simulation. We will try to find optimal combinations of these. Must have at least 1 item per slot so it is possible to form a full equipment set.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationConfigTopGearKind `json:"kind"`
}

// SimulationConfigTopGearKind defines model for SimulationConfigTopGear.Kind.
type SimulationConfigTopGearKind string

// SimulationCoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
type SimulationCoreConfig struct {
	// FightStyle Simc fight style
	FightStyle *FightStyle `json:"fight_style,omitempty"`
}

// SimulationKind The concrete kind of simulation to perform (basic, topGear, etc.)
type SimulationKind string

// SimulationOptions defines model for simulation_options.
type SimulationOptions struct {
	union json.RawMessage
}

// SimulationResult Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
type SimulationResult struct {
	union json.RawMessage
}

// SimulationResultBasic Result of a `basic` simulation — a single actor simmed with their equipped gear. For now this just surfaces the headline DPS and the raw simc log; it will grow structured stats later.
type SimulationResultBasic struct {
	// Dps Mean DPS of the simmed actor.
	Dps  float64                   `json:"dps"`
	Kind SimulationResultBasicKind `json:"kind"`

	// RawLog Human-readable stdout from simc. Optional; may be truncated or omitted for large runs.
	RawLog *string `json:"raw_log,omitempty"`
}

// SimulationResultBasicKind defines model for SimulationResultBasic.Kind.
type SimulationResultBasicKind string

// SimulationResultTopGear Result of a `topGear` simulation.
// To keep payload size bounded when many profilesets are generated, items are sent once in `equipment` and each profileset references them by index. A profileset's `head: 3` means "the item at equipment[3]". Indices are stable for the lifetime of this result object; they are NOT indices into the request's equipment array (the worker may have reordered/deduplicated).
type SimulationResultTopGear struct {
	// Equipment Item table for this result. Every integer slot value inside `profilesets[*].items` is an index into this array.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationResultTopGearKind `json:"kind"`

	// Metric The statistic `mean` on each profileset refers to. Copied from simc's `sim.profilesets.metric` — usually "dps".
	Metric string `json:"metric"`

	// Profilesets All simmed loadouts, sorted by `mean` descending (best first).
	Profilesets []TopGearProfilesetResult `json:"profilesets"`
}

// SimulationResultTopGearKind defines model for SimulationResultTopGear.Kind.
type SimulationResultTopGearKind string

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// TopGearProfilesetItems Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
type TopGearProfilesetItems struct {
	Back     int `json:"back"`
	Chest    int `json:"chest"`
	Feet     int `json:"feet"`
	Finger1  int `json:"finger1"`
	Finger2  int `json:"finger2"`
	Hands    int `json:"hands"`
	Head     int `json:"head"`
	Legs     int `json:"legs"`
	MainHand int `json:"main_hand"`
	Neck     int `json:"neck"`

	// OffHand Absent when this loadout has no off-hand (two-hander).
	OffHand  *int `json:"off_hand,omitempty"`
	Shoulder int  `json:"shoulder"`
	Trinket1 int  `json:"trinket1"`
	Trinket2 int  `json:"trinket2"`
	Waist    int  `json:"waist"`
	Wrist    int  `json:"wrist"`
}

// TopGearProfilesetResult One simmed loadout and its headline metric.
type TopGearProfilesetResult struct {
	// Items Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
	Items TopGearProfilesetItems `json:"items"`

	// Mean Mean of `metric` (typically DPS) for this loadout.
	Mean float64 `json:"mean"`

	// MeanError simc's reported error bound on `mean`.
	MeanError *float64 `json:"mean_error,omitempty"`

	// Name Profileset label as generated by the worker (e.g. "Combo7"). Matches `sim.profilesets.results[].name` in the raw simc json2 blob, which is how the worker joins metrics to loadouts.
	Name string `json:"name"`
}

// WowCharacter The representation of a wow character.
type WowCharacter struct {
	// ActiveTalents A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
	ActiveTalents CharacterTalentLoadout `json:"active_talents"`

	// BagItems Items in the character's bags
	BagItems *[]EquipmentItem `json:"bag_items,omitempty"`

	// CatalystCurrencies Catalyst charges
	CatalystCurrencies *[]struct {
		// Id The id of the currency
		Id int `json:"id"`

		// Quantity The quantity of the currency the character has
		Quantity int `json:"quantity"`
	} `json:"catalyst_currencies,omitempty"`
	CharacterClass CharacterClass `json:"character_class"`

	// EquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
	EquippedItems CharacterEquippedItems `json:"equipped_items"`
	Level         int                    `json:"level"`

	// LootSpec The loot specialization of your character.
	LootSpec *string `json:"loot_spec,omitempty"`

	// Name Name of the character
	Name               *string                       `json:"name,omitempty"`
	Professions        *string                       `json:"professions"`
	Race               string                        `json:"race"`
	Region             *string                       `json:"region"`
	Role               *string                       `json:"role"`
	Server             *string                       `json:"server"`
	SlotHighWatermarks *[]CharacterSlotHighWatermark `json:"slot_high_watermarks,omitempty"`
	Spec               string                        `json:"spec"`

	// TalentLoadouts The talent loadouts that were not active
	TalentLoadouts      *[]CharacterTalentLoadout `json:"talent_loadouts,omitempty"`
	UpgradeAchievements *[]int                    `json:"upgrade_achievements,omitempty"`
}

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// MalformedRequest Error response returned by API when something goes wrong
type MalformedRequest = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions

// AsSimulationConfigBasic returns the union data inside the SimulationOptions as a SimulationConfigBasic
func (t SimulationOptions) AsSimulationConfigBasic() (SimulationConfigBasic, error) {
	var body SimulationConfigBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigBasic overwrites any union data inside the SimulationOptions as the provided SimulationConfigBasic
func (t *SimulationOptions) FromSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigBasic performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigBasic
func (t *SimulationOptions) MergeSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationConfigTopGear returns the union data inside the SimulationOptions as a SimulationConfigTopGear
func (t SimulationOptions) AsSimulationConfigTopGear() (SimulationConfigTopGear, error) {
	var body SimulationConfigTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigTopGear overwrites any union data inside the SimulationOptions as the provided SimulationConfigTopGear
func (t *SimulationOptions) FromSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigTopGear performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigTopGear
func (t *SimulationOptions) MergeSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationOptions) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationOptions) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationConfigBasic()
	case "topGear":
		return t.AsSimulationConfigTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationOptions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationOptions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSimulationResultBasic returns the union data inside the SimulationResult as a SimulationResultBasic
func (t SimulationResult) AsSimulationResultBasic() (SimulationResultBasic, error) {
	var body SimulationResultBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultBasic overwrites any union data inside the SimulationResult as the provided SimulationResultBasic
func (t *SimulationResult) FromSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultBasic performs a merge with any union data inside the SimulationResult, using the provided SimulationResultBasic
func (t *SimulationResult) MergeSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationResultTopGear returns the union data inside the SimulationResult as a SimulationResultTopGear
func (t SimulationResult) AsSimulationResultTopGear() (SimulationResultTopGear, error) {
	var body SimulationResultTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultTopGear overwrites any union data inside the SimulationResult as the provided SimulationResultTopGear
func (t *SimulationResult) FromSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultTopGear performs a merge with any union data inside the SimulationResult, using the provided SimulationResultTopGear
func (t *SimulationResult) MergeSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationResultBasic()
	case "topGear":
		return t.AsSimulationResultTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	Health(c *gin.Context)

	// (POST /simulation)
	Simulate(c *gin.Context)

	// (GET /simulation/{id})
	GetSimulation(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// Simulate operation middleware
func (siw *ServerInterfaceWrapper) Simulate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Simulate(c)
}

// GetSimulation operation middleware
func (siw *ServerInterfaceWrapper) GetSimulation(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSimulation(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.Health)
	router.POST(options.BaseURL+"/simulation", wrapper.Simulate)
	router.GET(options.BaseURL+"/simulation/:id", wrapper.GetSimulation)
}

type BadRequestErrorJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type MalformedRequestJSONResponse ErrorResponse

type NotFoundErrorJSONResponse ErrorResponse

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse HealthResponse

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimulateRequestObject struct {
	Body *SimulateJSONRequestBody
}

type SimulateResponseObject interface {
	VisitSimulateResponse(w http.ResponseWriter) error
}

type Simulate202JSONResponse struct {
	// SimulationId ID of the simulation that was created
	SimulationId *string `json:"simulation_id,omitempty"`
}

func (response Simulate202JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type Simulate400JSONResponse ErrorResponse

func (response Simulate400JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Simulate401JSONResponse ErrorResponse

func (response Simulate401JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Simulate404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response Simulate404JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type Simulate422JSONResponse struct{ MalformedRequestJSONResponse }

func (response Simulate422JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type Simulate500JSONResponse struct{ InternalErrorJSONResponse }

func (response Simulate500JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulationRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSimulationResponseObject interface {
	VisitGetSimulationResponse(w http.ResponseWriter) error
}

type GetSimulation200JSONResponse Simulation

func (response GetSimulation200JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response GetSimulation404JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSimulation500JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (POST /simulation)
	Simulate(ctx context.Context, request SimulateRequestObject) (SimulateResponseObject, error)

	// (GET /simulation/{id})
	GetSimulation(ctx context.Context, request GetSimulationRequestObject) (GetSimulationResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *gin.Context) {
	var request HealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Simulate operation middleware
func (sh *strictHandler) Simulate(ctx *gin.Context) {
	var request SimulateRequestObject

	var body SimulateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Simulate(ctx, request.(SimulateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Simulate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SimulateResponseObject); ok {
		if err := validResponse.VisitSimulateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSimulation operation middleware
func (sh *strictHandler) GetSimulation(ctx *gin.Context, id openapi_types.UUID) {
	var request GetSimulationRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSimulation(ctx, request.(GetSimulationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSimulation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSimulationResponseObject); ok {
		if err := validResponse.VisitGetSimulationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Q77XLjRnKv0oWkyrspiFpp95KcXPkhr3227mJb5ZWzlVqpoCHQJGYFzGBnBuLyXKzK",
	"Q+QJ8ySp7hmAQwIUKca+c/bPisD0TH9Nf+OXJNd1oxUqZ5OLXxKDttHKIv+YiiIz+KlF6zI0Rht6mGvl",
	"UDn6UzRNJXPhpFanH61W9MzmJdaC/vpHg7PkIvmH0/UJp/6tPeXdsu6wZLVapUmBNjeyod2Si+QndK1R",
	"WMCiRAWuRAiYgLRQi2qmTY0FaAOEkJDKglSPopIFSNW0bpKs0kQqh0aJ6u+LPT6iAaGgwwYsGnrE24DO",
	"89bYCdyU0kJrW1FVS6hRKMtU56K1CDNt+JcHWQgLunWgZ36JVs7oqv8pqgoN09/zqRPj35AF3zCq3Qow",
	"HUemS7i8vvJibS0aLy6YCVlhARZroZzMgUXJmBEhSrtspltV/A70UDQSct1WBSjtoNK5cAiiU08siGbd",
	"mhwnCW0XjmKUS2FE7tBkeSUsP0LV1snFh2QhjJHaJGlStqQmSZrUWj0kadKIShRSJWli9LzFJE1sKWpB",
	"D2oxp98LYSqd09rCtLKg/1G48kHJeeloByNJ9PS41qrfHx/1A5rkLk3cssHkIrHOSDUndq8RxU+tbBos",
	"MumwZow32XNFj8GVwnnd6wAhb41B5aollMJCt00KD7j0SsCPalQObKXdBO71bJaVQhX3dMN1LZ2Lub7e",
	"ubVoQYBb6BNaTotQNFpNbhUTqxs0TnYWLH/YqwMdIkyjJz9cleeBzRCPgZJqjubsWMDz5wMS1+wRYCiK",
	"50NVOD/irFpIxcrwfFCFx4i8U77nQ9qSbAGa50PSdXtAd3Y05BGyXwh5jGovzBFgqzQhoygNFmTiWH+C",
	"fCK2pf6SdreuO6tT0w7loEnhlq2vzfoeRAyNOBTr0trU6elHzN2mqSMzlJVyXmYL4dDUwjwM7d1NbIq+",
	"sJ2ZA6EKIFgKUFpF5hgLaJu5EQWCMyJ/AGIKVPiIlWV/LsA2mMuZzGGOwrAZhJnRNVwWhaTzRAVve7N3",
	"pWZ6MjBw4XzmeMab09NAJQUcczT+Qn3eu4YQOFzGvHpbxvwwHcNqgMLTwnCiog0qLQrduqEcLsGKRyzA",
	"r4OwDrwLS6ERhBEspCvZeyhRYxcfhbUT+E/dQi4U4OdGG/Jf0nr+06p3ss5BFIVW8EIbqIXykZlfwKda",
	"qFG1IBXMRY0vh8KhU8dVKMZnkwTaZeCPw3nje73X77s9AsRghy0pdduNiWDrEl/8su1RtWptJr0D6YOC",
	"oTKFJ8IYsWTRGjFzWGTWCXcUrFTz7FMrKumWzNu2qsS0wuTCmRbTkV0KaZtKLLNOCgOuospLQYQWh204",
	"x/oIwlnl/RHDxZtXcj8KO2kxYpFVUo2/POZip4kPYp8B59fvMAmM+ZZQ1szpT4soeVo7O5q6APrv712i",
	"IIIQkIY2cmIqTDEaZA84F1HTxcuM/3wcfDN1GZiGQ/Ivq2t0pVRzmGu0sDCarceWi9HFzu353QhyNVpL",
	"yckA7Hv/gmxuJaSio/u8dq/d6nZNPU5jCjKjnCezblmNHM42nVeAX5H2DG+Ey8sFGs6iWjVHrTJbSdZI",
	"J8wcXVa0db0kkM+Ytw6zGKTE3Mk8E0WR5RWKRwKrGJVaPyIJmReJx2X8IBeWzVq8kwennUalXqKoXLkh",
	"9k1pkX1tfWr5WdQNsSEALffyN8CO8dXKuq18Oj5g67WuKhIkqkesdINddNODwEc9HXpHr8AOP7uxLRuC",
	"7RJAjxj8m9eTURfpLexWcvp1XziJkCEc+K8JC7Nj0psz/KM4P5+dFOf52cmbf52en0zPX785OftDMX3z",
	"z2ev3vyxeEP2QJtauOQiaX2qPUDkQe7PItbYZLyc5WDbyj0DMACQbHqRHwgaALbFz/QwPulhqpDlWs3k",
	"PJsKK/OR6+bDW7Sb3Kf/LDgNFlVB/5N8Lq+vRoLbLhzcR9tCL7L1YooYtMGA3TP4EkNFkuxshCfzbt8t",
	"Chxc47OJzmEsdbr5FoUZifh0E9KFAU8nQOEgv1yUMi9hgeAdITizJE7PpCrY6DNILSrIdT2VKmwz+92J",
	"oPeR46Ev0+o05FpZWXAtceu2T+A9wkJW1QYLRqi3IRy3OIHvW+ugFI8IwkGFwjo48+lbgyFPsxokl6Ib",
	"ba2cVsh7a1ODgFlbVXF5Czmo70PGZ6b6W+HktlJ2irJXLWPOxoxNhwq7V0U3JLsplrfaMP9z8Ct8bVBa",
	"sKWglGyKboGoQFRVrMKEg4UXfMVScEHJU0CXT14OtHLLyz/F0XjpavU0YR1vR1J+rXKDDhlP0pQIdadJ",
	"LVj2Ef7fbqC/aULSJ6S2gVC42IyTJJxq0lZt9iC5xdcIQw5Ym4ZO4uoo2+0DLmVk5tfIHwzYAax6OS5/",
	"4EQm6byfVvjjLLn48Aw7EaG0Sp8L12O0R9XXXnmL3csGC9Cta3wbRpApaSqkiCU2PtzUkb6T8yiqFvmv",
	"hTYPaGBhpEP2hPcRjJV1OPa+M2eFoDTCIleZgrcMAb2FRzRT4WT9Zf+moFheaQcGCavWIdkqrcCgKHyV",
	"fKBNR2iFR/IIrQiAv4FWbKD0DK3YxuhuTAt2hTk/8VuvBfe85j6+gf/zX//NwbCaVwgid5pddx1Vp6Tp",
	"+yNs9SbwJ21A6YUvSX0kb2RbMxM5ek2iXJdSZPj6+l2vE0YsvN2t9PxLEjh7vbnRC7DOtLlryfxy+QUo",
	"tDZj/ZKisWM5m1B8VChYBfSZlkkcEhe6nVZRPqjaeuqDgUNDqZD+6xHH8l1bC3VCKizI3VrHBT8uxxHZ",
	"E/ix8TXTL6EWS5giONOqnJMIbfqGEiUEFSV0YFplPQ8OiueINQdZi92x24amhFWxrkxu1Y2GB8QGGrGs",
	"tCBj8leEqW59n4tyoVqoJTRGz2SFFp0FYSgQUpTUYJFynOIfWoo+tMqR7Mh97/HvWWVQ5GW0DRicoUEV",
	"VKyG6RKkKvDzBC6jZV9YuCftu4DX96FJfZuQTnB0JNw67Pnw+u42mcCVKiTtyfg4llyXklVyhk52dVBp",
	"wQT2MGvZnC0Z7ocfbwgX3keqkDCEdusXNoq0OEiCF5GJJU3gQM6gNgUaLE4LLFrfLsbi5dgdeCLmvCIq",
	"Yyp6rCfwzSOaJYRanQ8SvcWXHJvCfSSzD/90N2E5ca+TRwMK/NwRR4+IEo/c3zxuTJManRmzdBRkkAGR",
	"1skc7kn+9+RXRnWJHNsE3upG0q3rrikpkJX1JGLGxB93z5ayG4C4pft2m3gWrJN0uoQjCEe7jbQKfKRJ",
	"JivU2G0KVhvni2GBDIJBVUg1hxdTtA5m0lj38hkyCBzN1shEOfqmOMYtTGD7ZnAek7bH/ESlnyBkqQib",
	"uUFLbJMq+9QijxB09bYuahlVgxGCdkwBXKM5YY2Ps54Kc3aAXTWIHWDffPHXJdyQ4R1AaAQ31jwLSW1i",
	"A8bXY9/IQNcUOmZgYFh674cChq+6xv/Im3Vzf9fL8/GXfZN+5FVoxA/fdM32sf5f1FAf6SvgLrLjxvjW",
	"vZqygwnslrbndyko/AQ9mzG/4UXPefMyqt3Fnceohz7SUYn65Dvf7mBj3+8eeWV2vPp/0bfebW0GgvpR",
	"4ZYB5AhAOruOJL3tGdZ/jrV8Ho59iVA7Qko9I+Prbf8Lt2xkzqb/6+t3L9fuNWqLHhBn0mnrEbHNM4P7",
	"Mdh42+9n6Ti2Iifm/cCB54x3dq/XLrASU6xA2HVkRr4mikxe4GQ+gdvkra6n+l9uk5cT+F440qWhg/SC",
	"tR/uJnRunxb2Ef9Hq9U5TCs9TUPlT1ooOX/oz/uopbJBzJxzdr7wkBA4dOtYlp03HFPKzSLgaPxgsDFI",
	"hqOrOYKAhV6shyqGOihyJx8xi5rgTynjzhmCFffSnh5kk1vDZl9YmAq+vr9SGJYLJ6qldZkfkci7vGuz",
	"hhYWMR5z3Dh+63ruqFfJop8G9ecsR+3up1YoFxrqw026t9tbbc3jlcKObD7WW+iPGzVo25waDkseJna/",
	"vCseb8wuHrbBFhz71dChr6WSNcVWZ2PsrLR2mW1wR+hMr/3Mj6jkX3v9X+rWbKr/IBIbNzc/REMkcbdh",
	"NDxGa7tS4o4xgzgHz3dMGeA8dAD376F9bXbvQj8MfdjS4YTW4U7q6UGvEQXsBLljGqezKzumcjanesKI",
	"7AINcmXOm7RDzcpTJm0b6zBzlom8lOg7zc+bWNm6uN301vb9GlyvwLCgPem21R5eeZZ93hrplu+IUG/R",
	"Lhv5F1xetq4caSgyPyie997UtDxvnVeSp7GYxaJ1JSrH+b2vsNH1ury+mtyqn62vv95fNvLkL7i8gNv2",
	"1avXuWhk9oBL/oH3HBQh95XizUImqHw/3UeA/l4mYbv11RNMBPH2KxQGTUfOlH/9qYsv/vz+JtmeN/8K",
	"HRlVgoA/v7/pieV09KQRxi3DhL/doKh1pTbBqlyAPzaQ93Hh9pJ2ox9Q2a5dOKWczLYhQf7qm5ubb37K",
	"Ln+++S77+ad/9/Uj0h/OpShSu393efXDTXZ5fcULPKtYe4kbnuo1d0rnGj9qL9VMj10faUOJm6ccZFw1",
	"skIqB9PWSoWWwsO5zH3js5A216aAqXYpoZhCox2R6L+o4L4UmsdQRuLNZq1rDaa+VEpc9TFnaEY76bjo",
	"8I6PvLy+StLkEY31WJ5NXk1ecYbUoBKNTC6S15NXk9c8su9KVuZTP3lBf87RjRUEfQ2fiPVLw6gDHd/P",
	"KVwVyUXynd8p3fxC5/zVq1/tW4jt0ZKRjyEIT2kDqssJLVmlyenmcEij7Sip/uudeC6EJEQmkdXsnazf",
	"Dsl+5xfzYJjf4StdLH81mkd6bSNk+0GG5dgYQ4kGJ0lsMsl3rQZiOn8WylsjPWskd0y5rAvzfVOS3Y2w",
	"kBuk7GM0xN82yEPC1xt2X1/RniLPsaFNV2ny5lfUwN/0q7CReQmP/9nvAv++aSdVXrUF+g+gYjNNmOcG",
	"C2/SOuzf7EKqV8DT7Y+nCO78fD/c8OuxVZr8wcv7acit7+5iV8/tvNgrfrhbpZtu/8Pd6m7Lrpz+IovV",
	"TjP6HxIXgZnrBkvUVhlYlW/RrVWbDbYRNTo0ltEbRnPjd0zDpxbNsgsLyOyvgwLOeDbNQhrp0Z45stXd",
	"b2jpI3s9oqM3m1R6nqagTQpywANpoy+9pIKu3JxGGaNjp4YjHOS5wP+DGh+njPTvfwMAAP//xL6KCvg6",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
