// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CharacterClass.
const (
	Deathknight CharacterClass = "deathknight"
	Demonhunter CharacterClass = "demonhunter"
	Druid       CharacterClass = "druid"
	Evoker      CharacterClass = "evoker"
	Hunter      CharacterClass = "hunter"
	Mage        CharacterClass = "mage"
	Monk        CharacterClass = "monk"
	Paladin     CharacterClass = "paladin"
	Priest      CharacterClass = "priest"
	Rogue       CharacterClass = "rogue"
	Shaman      CharacterClass = "shaman"
	Warlock     CharacterClass = "warlock"
	Warrior     CharacterClass = "warrior"
)

// Defines values for EquipmentSlot.
const (
	Back     EquipmentSlot = "back"
	Chest    EquipmentSlot = "chest"
	Feet     EquipmentSlot = "feet"
	Finger1  EquipmentSlot = "finger1"
	Finger2  EquipmentSlot = "finger2"
	Hands    EquipmentSlot = "hands"
	Head     EquipmentSlot = "head"
	Legs     EquipmentSlot = "legs"
	MainHand EquipmentSlot = "main_hand"
	Neck     EquipmentSlot = "neck"
	OffHand  EquipmentSlot = "off_hand"
	Shirt    EquipmentSlot = "shirt"
	Shoulder EquipmentSlot = "shoulder"
	Tabard   EquipmentSlot = "tabard"
	Trinket1 EquipmentSlot = "trinket1"
	Trinket2 EquipmentSlot = "trinket2"
	Waist    EquipmentSlot = "waist"
	Wrist    EquipmentSlot = "wrist"
)

// Defines values for EquipmentSource.
const (
	Bag      EquipmentSource = "bag"
	Equipped EquipmentSource = "equipped"
)

// Defines values for FightStyle.
const (
	CastingPatchwerk FightStyle = "CastingPatchwerk"
	CleaveAdd        FightStyle = "CleaveAdd"
	DungeonSlice     FightStyle = "DungeonSlice"
	ExecutePatchwerk FightStyle = "ExecutePatchwerk"
	HeavyMovement    FightStyle = "HeavyMovement"
	HecticAddCleave  FightStyle = "HecticAddCleave"
	LightMovement    FightStyle = "LightMovement"
	Patchwerk        FightStyle = "Patchwerk"
)

// Defines values for SimulationConfigBasicKind.
const (
	SimulationConfigBasicKindBasic SimulationConfigBasicKind = "basic"
)

// Defines values for SimulationConfigTopGearKind.
const (
	SimulationConfigTopGearKindTopGear SimulationConfigTopGearKind = "topGear"
)

// Defines values for SimulationKind.
const (
	SimulationKindBasic   SimulationKind = "basic"
	SimulationKindTopGear SimulationKind = "topGear"
)

// Defines values for SimulationResultBasicKind.
const (
	Basic SimulationResultBasicKind = "basic"
)

// Defines values for SimulationResultTopGearKind.
const (
	SimulationResultTopGearKindTopGear SimulationResultTopGearKind = "topGear"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// CharacterClass defines model for character_class.
type CharacterClass string

// CharacterEquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
type CharacterEquippedItems struct {
	Back     EquipmentItem  `json:"back"`
	Chest    EquipmentItem  `json:"chest"`
	Feet     EquipmentItem  `json:"feet"`
	Finger1  EquipmentItem  `json:"finger1"`
	Finger2  EquipmentItem  `json:"finger2"`
	Hands    EquipmentItem  `json:"hands"`
	Head     EquipmentItem  `json:"head"`
	Legs     EquipmentItem  `json:"legs"`
	MainHand EquipmentItem  `json:"main_hand"`
	Neck     EquipmentItem  `json:"neck"`
	OffHand  *EquipmentItem `json:"off_hand,omitempty"`
	Shoulder EquipmentItem  `json:"shoulder"`
	Trinket1 EquipmentItem  `json:"trinket1"`
	Trinket2 EquipmentItem  `json:"trinket2"`
	Waist    EquipmentItem  `json:"waist"`
	Wrist    EquipmentItem  `json:"wrist"`
}

// CharacterSlotHighWatermark The character's current and highest unlocked upgrade track item levels for a specific gear slot from Additional Character Info.
type CharacterSlotHighWatermark struct {
	CurrentItemLevel int           `json:"current_item_level"`
	MaxItemLevel     int           `json:"max_item_level"`
	Slot             EquipmentSlot `json:"slot"`
}

// CharacterTalentLoadout A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
type CharacterTalentLoadout struct {
	// Name The name of the talent loadout.
	Name *string `json:"name,omitempty"`

	// Talents The WoW talent string
	Talents string `json:"talents"`
}

// EquipmentItem defines model for equipment_item.
type EquipmentItem struct {
	BonusIds        *[]int          `json:"bonus_ids,omitempty"`
	CraftedStats    *[]int          `json:"crafted_stats,omitempty"`
	CraftingQuality *int            `json:"crafting_quality"`
	DisplayName     string          `json:"display_name"`
	EnchantId       *int            `json:"enchant_id"`
	GemIds          *[]int          `json:"gem_ids,omitempty"`
	ItemId          int             `json:"item_id"`
	ItemLevel       *int            `json:"item_level"`
	Name            string          `json:"name"`
	RawLine         string          `json:"raw_line"`
	Slot            EquipmentSlot   `json:"slot"`
	Source          EquipmentSource `json:"source"`
}

// EquipmentSlot defines model for equipment_slot.
type EquipmentSlot string

// EquipmentSource defines model for equipment_source.
type EquipmentSource string

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Code Error code
	Code string `json:"code"`

	// Message Message explaining the error
	Message string `json:"message"`
}

// FightStyle Simc fight style. For up-to-date list of supported fight styles, check the simc repo:
//
//	https://github.com/simulationcraft/simc/blob/5e3d3bcf9d6437c82330ff3826041df164b535a1/engine/util/util.cpp#L566
type FightStyle string

// HealthResponse defines model for health_response.
type HealthResponse struct {
	Status string `json:"status"`
}

// Simulation Polling envelope for a simulation job.
type Simulation struct {
	// ErrorText Populated when status = error.
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation.
	Id openapi_types.UUID `json:"id"`

	// Kind The concrete kind of simulation to perform (basic, topGear, etc.)
	Kind SimulationKind `json:"kind"`

	// RawSimcInput The raw SIMC input for the sim
	RawSimcInput *string `json:"raw_simc_input,omitempty"`

	// Result Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
	Result *SimulationResult `json:"result,omitempty"`
	Status SimulationStatus  `json:"status"`
}

// SimulationConfigBasic Specifies simulation options to send to the API.
type SimulationConfigBasic struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig      `json:"core_config"`
	Kind       SimulationConfigBasicKind `json:"kind"`
}

// SimulationConfigBasicKind defines model for SimulationConfigBasic.Kind.
type SimulationConfigBasicKind string

// SimulationConfigTopGear Top gear simulation options. The gear which we should try to find some optimal combination of.
type SimulationConfigTopGear struct {
	// Character The representation of a wow character.
	Character WowCharacter `json:"character"`

	// CoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
	CoreConfig SimulationCoreConfig `json:"core_config"`

	// Equipment The gear to consider in the simulation. We will try to find optimal combinations of these. Must have at least 1 item per slot so it is possible to form a full equipment set.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationConfigTopGearKind `json:"kind"`
}

// SimulationConfigTopGearKind defines model for SimulationConfigTopGear.Kind.
type SimulationConfigTopGearKind string

// SimulationCoreConfig Core simc config that is shared between all simulation kinds (basic, top gear, etc.)
type SimulationCoreConfig struct {
	// FightStyle Simc fight style. For up-to-date list of supported fight styles, check the simc repo:
	//  https://github.com/simulationcraft/simc/blob/5e3d3bcf9d6437c82330ff3826041df164b535a1/engine/util/util.cpp#L566
	FightStyle *FightStyle `json:"fight_style,omitempty"`
}

// SimulationKind The concrete kind of simulation to perform (basic, topGear, etc.)
type SimulationKind string

// SimulationOptions defines model for simulation_options.
type SimulationOptions struct {
	union json.RawMessage
}

// SimulationResult Typed output of a completed simulation. This is the value the worker writes to `simulation.sim_result` in the database and the API returns verbatim; the API does not recompute it on read.
type SimulationResult struct {
	union json.RawMessage
}

// SimulationResultBasic Result of a `basic` simulation — a single actor simmed with their equipped gear. For now this just surfaces the headline DPS and the raw simc log; it will grow structured stats later.
type SimulationResultBasic struct {
	// Dps Mean DPS of the simmed actor.
	Dps  float64                   `json:"dps"`
	Kind SimulationResultBasicKind `json:"kind"`

	// RawLog Human-readable stdout from simc. Optional; may be truncated or omitted for large runs.
	RawLog *string `json:"raw_log,omitempty"`
}

// SimulationResultBasicKind defines model for SimulationResultBasic.Kind.
type SimulationResultBasicKind string

// SimulationResultTopGear Result of a `topGear` simulation.
// To keep payload size bounded when many profilesets are generated, items are sent once in `equipment` and each profileset references them by index. A profileset's `head: 3` means "the item at equipment[3]". Indices are stable for the lifetime of this result object; they are NOT indices into the request's equipment array (the worker may have reordered/deduplicated).
type SimulationResultTopGear struct {
	// Equipment Item table for this result. Every integer slot value inside `profilesets[*].items` is an index into this array.
	Equipment []EquipmentItem             `json:"equipment"`
	Kind      SimulationResultTopGearKind `json:"kind"`

	// Metric The statistic `mean` on each profileset refers to. Copied from simc's `sim.profilesets.metric` — usually "dps".
	Metric string `json:"metric"`

	// Profilesets All simmed loadouts, sorted by `mean` descending (best first).
	Profilesets []TopGearProfilesetResult `json:"profilesets"`
}

// SimulationResultTopGearKind defines model for SimulationResultTopGear.Kind.
type SimulationResultTopGearKind string

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// TopGearProfilesetItems Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
type TopGearProfilesetItems struct {
	Back     int `json:"back"`
	Chest    int `json:"chest"`
	Feet     int `json:"feet"`
	Finger1  int `json:"finger1"`
	Finger2  int `json:"finger2"`
	Hands    int `json:"hands"`
	Head     int `json:"head"`
	Legs     int `json:"legs"`
	MainHand int `json:"main_hand"`
	Neck     int `json:"neck"`

	// OffHand Absent when this loadout has no off-hand (two-hander).
	OffHand  *int `json:"off_hand,omitempty"`
	Shoulder int  `json:"shoulder"`
	Trinket1 int  `json:"trinket1"`
	Trinket2 int  `json:"trinket2"`
	Waist    int  `json:"waist"`
	Wrist    int  `json:"wrist"`
}

// TopGearProfilesetResult One simmed loadout and its headline metric.
type TopGearProfilesetResult struct {
	FirstQuartile float64 `json:"first_quartile"`

	// Items Per-slot equipment selection for a single loadout. Every value is an index into the parent result's `equipment` array. `off_hand` is omitted when the loadout uses a two-handed weapon.
	Items      TopGearProfilesetItems `json:"items"`
	Iterations int                    `json:"iterations"`
	Max        float64                `json:"max"`

	// Mean Mean of `metric` (typically DPS) for this loadout.
	Mean float64 `json:"mean"`

	// MeanError simc's reported error bound on `mean`.
	MeanError  float64 `json:"mean_error"`
	MeanStddev float64 `json:"mean_stddev"`
	Median     float64 `json:"median"`
	Min        float64 `json:"min"`

	// Name Profileset label as generated by the worker (e.g. "Combo7"). Matches `sim.profilesets.results[].name` in the raw simc json2 blob, which is how the worker joins metrics to loadouts.
	Name          string  `json:"name"`
	Stddev        float64 `json:"stddev"`
	ThirdQuartile float64 `json:"third_quartile"`
}

// WowCharacter The representation of a wow character.
type WowCharacter struct {
	// ActiveTalents A saved talent loadout string, paired with the name of the loadout. You can export this from the Simc addon (or manually from talents menu in game).
	ActiveTalents CharacterTalentLoadout `json:"active_talents"`

	// BagItems Items in the character's bags
	BagItems *[]EquipmentItem `json:"bag_items,omitempty"`

	// CatalystCurrencies Catalyst charges
	CatalystCurrencies *[]struct {
		// Id The id of the currency
		Id int `json:"id"`

		// Quantity The quantity of the currency the character has
		Quantity int `json:"quantity"`
	} `json:"catalyst_currencies,omitempty"`
	CharacterClass CharacterClass `json:"character_class"`

	// EquippedItems Items that the character currently has equipped, keyed by equipment slot. `off_hand` is omitted when the character uses a two-handed weapon.
	EquippedItems CharacterEquippedItems `json:"equipped_items"`
	Level         int                    `json:"level"`

	// LootSpec The loot specialization of your character.
	LootSpec *string `json:"loot_spec,omitempty"`

	// Name Name of the character
	Name               *string                       `json:"name,omitempty"`
	Professions        *string                       `json:"professions"`
	Race               string                        `json:"race"`
	Region             *string                       `json:"region"`
	Role               *string                       `json:"role"`
	Server             *string                       `json:"server"`
	SlotHighWatermarks *[]CharacterSlotHighWatermark `json:"slot_high_watermarks,omitempty"`
	Spec               string                        `json:"spec"`

	// TalentLoadouts The talent loadouts that were not active
	TalentLoadouts      *[]CharacterTalentLoadout `json:"talent_loadouts,omitempty"`
	UpgradeAchievements *[]int                    `json:"upgrade_achievements,omitempty"`
}

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// MalformedRequest Error response returned by API when something goes wrong
type MalformedRequest = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions

// AsSimulationConfigBasic returns the union data inside the SimulationOptions as a SimulationConfigBasic
func (t SimulationOptions) AsSimulationConfigBasic() (SimulationConfigBasic, error) {
	var body SimulationConfigBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigBasic overwrites any union data inside the SimulationOptions as the provided SimulationConfigBasic
func (t *SimulationOptions) FromSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigBasic performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigBasic
func (t *SimulationOptions) MergeSimulationConfigBasic(v SimulationConfigBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationConfigTopGear returns the union data inside the SimulationOptions as a SimulationConfigTopGear
func (t SimulationOptions) AsSimulationConfigTopGear() (SimulationConfigTopGear, error) {
	var body SimulationConfigTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationConfigTopGear overwrites any union data inside the SimulationOptions as the provided SimulationConfigTopGear
func (t *SimulationOptions) FromSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationConfigTopGear performs a merge with any union data inside the SimulationOptions, using the provided SimulationConfigTopGear
func (t *SimulationOptions) MergeSimulationConfigTopGear(v SimulationConfigTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationOptions) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationOptions) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationConfigBasic()
	case "topGear":
		return t.AsSimulationConfigTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationOptions) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationOptions) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSimulationResultBasic returns the union data inside the SimulationResult as a SimulationResultBasic
func (t SimulationResult) AsSimulationResultBasic() (SimulationResultBasic, error) {
	var body SimulationResultBasic
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultBasic overwrites any union data inside the SimulationResult as the provided SimulationResultBasic
func (t *SimulationResult) FromSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultBasic performs a merge with any union data inside the SimulationResult, using the provided SimulationResultBasic
func (t *SimulationResult) MergeSimulationResultBasic(v SimulationResultBasic) error {
	v.Kind = "basic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimulationResultTopGear returns the union data inside the SimulationResult as a SimulationResultTopGear
func (t SimulationResult) AsSimulationResultTopGear() (SimulationResultTopGear, error) {
	var body SimulationResultTopGear
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimulationResultTopGear overwrites any union data inside the SimulationResult as the provided SimulationResultTopGear
func (t *SimulationResult) FromSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimulationResultTopGear performs a merge with any union data inside the SimulationResult, using the provided SimulationResultTopGear
func (t *SimulationResult) MergeSimulationResultTopGear(v SimulationResultTopGear) error {
	v.Kind = "topGear"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SimulationResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SimulationResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "basic":
		return t.AsSimulationResultBasic()
	case "topGear":
		return t.AsSimulationResultTopGear()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SimulationResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SimulationResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	Health(c *gin.Context)

	// (POST /simulation)
	Simulate(c *gin.Context)

	// (GET /simulation/{id})
	GetSimulation(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// Simulate operation middleware
func (siw *ServerInterfaceWrapper) Simulate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Simulate(c)
}

// GetSimulation operation middleware
func (siw *ServerInterfaceWrapper) GetSimulation(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSimulation(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.Health)
	router.POST(options.BaseURL+"/simulation", wrapper.Simulate)
	router.GET(options.BaseURL+"/simulation/:id", wrapper.GetSimulation)
}

type BadRequestErrorJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type MalformedRequestJSONResponse ErrorResponse

type NotFoundErrorJSONResponse ErrorResponse

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse HealthResponse

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimulateRequestObject struct {
	Body *SimulateJSONRequestBody
}

type SimulateResponseObject interface {
	VisitSimulateResponse(w http.ResponseWriter) error
}

type Simulate202JSONResponse struct {
	// SimulationId ID of the simulation that was created
	SimulationId *string `json:"simulation_id,omitempty"`
}

func (response Simulate202JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type Simulate400JSONResponse ErrorResponse

func (response Simulate400JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Simulate401JSONResponse ErrorResponse

func (response Simulate401JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Simulate404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response Simulate404JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type Simulate422JSONResponse struct{ MalformedRequestJSONResponse }

func (response Simulate422JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type Simulate500JSONResponse struct{ InternalErrorJSONResponse }

func (response Simulate500JSONResponse) VisitSimulateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulationRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSimulationResponseObject interface {
	VisitGetSimulationResponse(w http.ResponseWriter) error
}

type GetSimulation200JSONResponse Simulation

func (response GetSimulation200JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response GetSimulation404JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSimulation500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSimulation500JSONResponse) VisitGetSimulationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (POST /simulation)
	Simulate(ctx context.Context, request SimulateRequestObject) (SimulateResponseObject, error)

	// (GET /simulation/{id})
	GetSimulation(ctx context.Context, request GetSimulationRequestObject) (GetSimulationResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *gin.Context) {
	var request HealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Simulate operation middleware
func (sh *strictHandler) Simulate(ctx *gin.Context) {
	var request SimulateRequestObject

	var body SimulateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Simulate(ctx, request.(SimulateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Simulate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SimulateResponseObject); ok {
		if err := validResponse.VisitSimulateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSimulation operation middleware
func (sh *strictHandler) GetSimulation(ctx *gin.Context, id openapi_types.UUID) {
	var request GetSimulationRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSimulation(ctx, request.(GetSimulationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSimulation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSimulationResponseObject); ok {
		if err := validResponse.VisitGetSimulationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Q723LbRpa/cgqzVbG3IOpqT6LUPiiOJ9FMnKgiZV1blopqAodEW0A33N0QzUmxaj9i",
	"v3C/ZOucboAAAYqkNpnJ5CEWgb6c+x2/RokuSq1QORud/xoZtKVWFvnHRKRjg58qtG6MxmhDDxOtHCpH",
	"f4qyzGUinNTq8KPVip7ZJMNC0F//ZnAanUd/OlzdcOjf2kM+bVxfFi2XyzhK0SZGlnRadB79jK4yClOY",
	"Z6jAZQgBEpAWCpFPtSkwBW2AABJSWZDqUeQyBanKyo2iZRxJ5dAokf9zocdHNCAU1NCARUOP+BjQSVIZ",
	"O4KbTFqobCXyfAEFCmUZ60RUFmGqDf/yW+bCgq4c6KlfopUzOm9+ijxHw/g3dKrZ+A8kwVsGtV4BpqbI",
	"ZAEXV5eerZVF49kFUyFzTMFiIZSTCTArGTJCRGk3nupKpX8AORSlhERXeQpKO8h1IhyCqMUTU8JZVybB",
	"UUTHhasY5EwYkTg04yQXlh+hqoro/EM0F8ZIbaI4yioSkyiOCq0eojgqRS5SqaI4MnpWYRRHNhOFoAeF",
	"mNHvuTC5TmhtaiqZ0r8oXPag5CxzdIKRxHp6XGjVnI+P+gFNdBdHblFidB5ZZ6SaEblXgOKnSpYlpmPp",
	"sGCIu+S5pMfgMuG87NUbIamMQeXyBWTCQn1MDA+48ELAjwpUDmyu3Qju9XQ6zoRK70nDdSGda1N9dXJl",
	"0YIAN9cHtJwWoSi1Gt0qRlaXaJysLVjysFUGakAYR49+UJX9tk0Rn7NLqhma4+duPNl/I1HNPmMbinT/",
	"XTnOnnFXIaRiYdh/q8LnsLwWvv132oxsAZr9d5K6PaA7fvbOZ/B+LuRzRHtunrFtGUdkFKXBlEwcy0/g",
	"T4tssVfSWuvqu2oxrUEOkhS0bKU2Kz1oEbRFobYsrUydnnzExHVNHZmhcSZn2XguHJpCmIe+vbtpm6Iv",
	"bG3mQKgUaC8FKJUic4wpVOXMiBTBGZE8ABEFcnzE3LI/F2BLTORUJjBDYdgMwtToAi7SVNJ9Ioc3jdm7",
	"VFM96hm4cD9TfMyH09OAJQUcMzReoT5vXUMA7M5jXr3OY34YD0HVA+FpZjiR0wG5FqmuXJ8PF2DFI6bg",
	"10FYB96FxVAKggjm0mXsPZQosI6PwtoR/JeuIBEK8HOpDfkvaT39adW1LBIQaaoVvNAGCqF8ZOYX8K0W",
	"ClQVSAUzUeDLPnPo1mERasPTRYFO6fnjcN/wWe/1+/qMsKN3whqX6uOGWLCmxOe/rntUrSo7lt6BNEFB",
	"X5jCE2GMWDBrjZg6TMfWCfesvVLNxp8qkUu3YNpWeS4mOUbnzlQYD5ySSlvmYjGuudCjKqokE4RoutuB",
	"MyyegTiLvL+iv7irkttB2IiLEfNxLtXwy+codhz5IHaPfX79BpPAkK8xZUWc5rYWJk9LZ41THUD/871L",
	"K4ggAKShg5yYCJMOBtk9yrWwqeNlhn82vL2buvRMwy75l9UFukyqGcw0WpgbzdZjzcXodOPx/G4AuAKt",
	"peSkt+2df0E2NxdS0dVNXrvVbtWnxh6mIQGZUs4ztm6RD1zONp1XAK8YwV+0gao8cPogpSwul5azaluV",
	"5BIwba+2MSQZJg8MsKWjDJb6/FZB5lxpzw8PZ9Jl1WSU6OLQyqLKOSNl40W/k8NJrieHr/A0PZ0k06/S",
	"12enf06+PDk9PZpOT788eX10dpxOj1+fTV6dvhLHh6hmUuFh5WTO/xslZfmnH169fs15Ti0pV8Il2RwN",
	"yfi3lZqhVte5ZE16+xmTymF7xfeYOJlcpOmbHMUjLfqBEHynH5EkkVeIx0Xr9xthyfS2D/F7L9Jhsc5Q",
	"5C7rCGZXnsgDVD75/SyKkhgVNi22SkDYO8T5FcX7jL/SeU6ihuoRc11iHX81W+CjnvT9t1cxh5/d0JEl",
	"7a1TVA8Y/IeX5EEn7n3AWvr8bVPaaQFDMPBfdM6KSGfH+JU4OZkepCfJ8cHZl5OTg8nJ6dnB8at0cvb6",
	"+Ojsq/SMLJY2hXDReVT5YkAPkAe5Pc9ZQTPm5cHFkBiPuWAzHIsYMYfry3dv6qLOCrchQAzaKnd7gBI2",
	"ELcbIdpxa9iwLlBMIcYw3k24xolWUzkbT4SVyYCJ8SE92i4/6R8LToNFldK/RJWLq8uBgL4OgbfhNtfz",
	"8WoxRUnaYIBuD7q0d7VkozYvHs27bXoZKLiCpwvObiR1uvwOhRmQLF2GFKlH0xGQ2PHLeSaTDOYI3vmD",
	"Mwui9FSqlB0dbylEDokuJlKFY6Z/OBY0ccGwijGuTkOilZUp10/X7McI3iPMZZ53SDCAvQ0piMURvKus",
	"g0w8IggHOQrr4NinrCWG3NRqkFx+L7W1cpIjn61NAQKmVZ63S3rIiUwTJu9Z3lgLodeFshaUrWLZpmyb",
	"sHFfYLeKaIezXba80SZEBH6Fr4dKCzYTlIZO0M0RFYg8b4swwWDhBatYDC4IeQzoktHLnlSuRTZPUbS9",
	"dLl8GrGatgNlDopd0CHDyVHRCnSnSSyY9y34v+uA3zUh8RNc6wAUFJthkgRTQdKqzRYg1+jagpCD9LKk",
	"m7gizHZ7B6VsmfkV8DtvrDcsGz4ufuTkLar9qVb40zQ6/7CHnWiBtIz33ddAtEXUV155jdyLElPQlSt9",
	"60mQKSlzpBiobXy4kSV99+pR5BXyX3NtHtDA3EiH7AnvW3usLMK197U5SwWlTha5sha8ZUhiLDyimQgn",
	"i6+bNynlL0o7MEhQVQ7JVmkFBkXqOwM9aXqGVHggnyEVYePvIBUdkPaQinWI7oakYFOY8zO/9VJwz2vu",
	"2xr4v//9Pxxeq1mOIBKn2XUXrYqcNE1PiK2eT8WUnvsy3EfyRrYyU5GglyTK73OpEL69um5kgsJNtru5",
	"nn1NDGevNzN6DtaZKnEVmV8uOQEF62aoR5SWdihPFYqvCkW6AD7jMmoH2amuJnkrB1ZVMfHBwK6hVCh5",
	"6AHH8n1VCHVAIizI3VrHRU4uQRLaI/ip9HXir6EQC5ggOFOphNMSbZomGoXhuTAzBFMp62mwUzxHpNnJ",
	"WmyO3TqSEla1ZWV0q240PCCWUIpFrgUZk78jTHTle3uUXRVCLaA0eipztOgsCEOBkKI0CdOY4xT/0FL0",
	"oVWCZEfuG49/zyKDIslax4DBKRpUQcQKmCxAqhQ/j+CitewLC/ckfedweh8a87cRyQRHR8Ktwp4Pp3e3",
	"0QguVSrpTIbHMefqRCiXU3Syrv1KCyaQh0nL5mzB+3786YZg4XOkCglDaDF/YVuRFgdJ8KJlYkkSOJAz",
	"qE2KBtPDFNPKt8gxfTmkA0/EnJeEZRuLBuoRvH1Es4BQn/RBorf4kmNTuG/x7MO/342YT9zf5XGIFD/X",
	"yNEjwsQD9w+PG+OoQGeGLB0FGWRApHUygXvi/z35lUFZIsc2gje6lKR1tZqSAFlZjFrEGPnr7tlS1kMf",
	"t6Rvt5EnwSrtJyUcALh12kB7xEeaZLJCX8HGYH1Ja7Ko0aA9qFKpZvBigtbBVBrrXu7Bg0DR8QqYVo7e",
	"ZcewhQlk7wbnbdS2mJ9WMSkwWSqCZmbQEtmkGn+qkMcm6hpjHbUMisEAQhsmH67QHLDEt7OeHBN2gHV9",
	"iR1g03Dy6hI0pK8DCKXgZqInIYlN24Cxemwbk6gbYc8Zkui3G5pBiP6rethh4M1qoGHTy5Phl81gwsCr",
	"MHzQf1MPGAz1PFtDBAO9FNyEdnsYYE2vJuxgArmlbeidCQo/QU+nTG940VDevGxVA9vd1tbcwEAXqTUb",
	"sPHtBjI2Pf6BV2bDq3+JXv1ma9Nj1E8K1wwgRwDS2VUk6W3PaCDTNtaNP1XCOOmT7R2iveeaS7/PH+CL",
	"vhul+fOOoJBx3xDR6inZfu96XrhFKRP2PN9eXb9cefdWJ3rH21ZTed07g/czGLopfnyRQzvyod4N7XOP",
	"dWmKjzvTIZWeErsslruuHO7qX61CgVxMMAdhVxEq+dxWhPYCR7MR3EZvdDHRf76NXo7gnXCkU/1AwQu4",
	"/XA3onub9LjJfD5arU5gkutJHCqg0kLGeVRz30ctlQ3izrl3HRMMpgJxtBeVXSZNup+2rBmb0AtmsfWM",
	"8NLeANJlfkfkGi7H62rbg6yjYrXCDpmZbll3uM+BpUFyBXUVGQTM9Xw1GtS3KiJx8hHHrVGOpyzFxkmY",
	"JXeEnx7HlGsjk19YmIiZ/e0C60Q4kS+sG/tBn6TOpLtV0bCI4Zhh5/ouaeSGCqRMm5lmf89i0JN+qoRy",
	"YSykf0j9dv2otanSTNiBw4e6Rc11gy5qnVL9kd/d2O6X1+2AzgTubges7eNIKcyZFFLJgqLl4yFy5lq7",
	"sS1xQzJEr/3kmsjl3xv5X+jKdMW/Z1aGDeePrVGodv9oMOFBa2sPuWFYpl1VSTbMyuAsdIm3n6G9Sdu6",
	"0I/077a0P2fYnSnajb9D44oDAlgzcsNMWW1XNsyWdWfTwqD3HA1yrdWbtF3NylMmbR3qMDk5Fkkm0c8i",
	"7Dd3taa49Qziun711CsQLEhPvG61+yrPvE8qI93imhD1Fu2ilH/DxUXlsoEWMdODMjQfF5iKvxpIcskz",
	"hUxiUbkMleOKja+ZknpdXF2ObtUv1lfU7y9KefA3XJzDbXV0dJqIUo4fcME/8J7DXOROYfuwkNsrP3Ph",
	"Y3qvl1E4bqV6gpEg2n6DwqCp0Znwr7/UXv6v72+i9a8mvkFHRpV2wF/f3zTIso8+KIVxi/Cdiu1gVLlM",
	"m2BVzsFfG9D7OHdbUbvRD6hs3QCeUJZtq1Dy+Obtzc3bn8cXv9x8P/7l5x98RZDkh7NjCn7vry8uf7wZ",
	"X1xd8gJPKpZeoobHekWdzLnSfzAi1VQPqY+0oWnBkzCyXQe0QioHk8pKhZYi7plMfCs7lTbRJoWJdjGB",
	"GEOpHaHovwviTiOax1AY5MOmlasMxr74TVT1YXwYL3DScRnpmq+8uLqM4ugRjfVQHo+ORkec85aoRCmj",
	"8+h0dDQ65Q9PXMbCfOinc+jPGbqhEq/vyhCyfmkYh6Hrm1mWyzQ6j773J8Xd78xOjo5+sy961sePBj7p",
	"ITilDaAuRrRkGUeH3QGiUttBVP03aO3ZIeIQmUQWs2tZvOmjfe0X83ijP+EbnS5+M5wHuqcDaPvRlMXQ",
	"YEqGBkdR22SS71r22HSyF8hrY18rIDdMQq1aLU2bmd2NsJAYpDxqsG+xbpD7iK8OrL8hpDNFkmBJhy7j",
	"6Ow3lMDf9dvGgQkYD//xHwL+pg0rVZJXKfrP+NpmmiBPDKbepNXQn20CqhHAw/VPAGnfycn2ff1vIJdx",
	"9Mrz++mda1+Ptl09N2jbXvHD3TLuuv0Pd8u7Nbty+KtMlxvN6H9KnAdirlpmrUZZz6p8h24l2mywjSjQ",
	"obEMXj+aG9YxDZ8qNIs6LCCzvwoKOOPpmoW4JUdbZg2Xd7+jpW/Z6wEZveli6WkagzYxyB4NpG19rygV",
	"1A2EuJUxOnZqOEBBnh39f4jx84SR/vu/AAAA///k2zFIvj0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
