// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package interfaces

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

// SimulationMessageBody This JSON object is included in a rabbitmq message, then that message gets published to the simulation_queue. Consumers of the simulation queue (simulation_worker) will use this JSON object to carry out the simulation.
type SimulationMessageBody struct {
	// SimulationId Used to identify a simulation request in postgres
	SimulationId *string `json:"simulation_id,omitempty"`
}

// SimulationOptions Specifices sim options, and the character of interest to sim, send this to the api
type SimulationOptions struct {
	// WowCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc.
	WowCharacter *WoWCharacter `json:"wow_character,omitempty"`
}

// SimulationResponse Object containing information about a simulation operation, returned from api
type SimulationResponse struct {
	// SimulationId Used to identify a simulation request in postgres
	SimulationId *string `json:"simulation_id,omitempty"`
}

// WoWCharacter Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc.
type WoWCharacter struct {
	// CharacterName The name of the WoW character
	CharacterName *string `json:"character_name,omitempty"`

	// Realm The realm which the character is located on
	Realm *string `json:"realm,omitempty"`

	// Region Identifies the region in which the characters realm is located
	Region *string `json:"region,omitempty"`
}

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
