// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api_types

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GearPreviewItemSource.
const (
	Bag      GearPreviewItemSource = "bag"
	Equipped GearPreviewItemSource = "equipped"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

// GearPreviewGroup defines model for gear_preview_group.
type GearPreviewGroup struct {
	Items []GearPreviewItem `json:"items"`
	Label string            `json:"label"`
	Slot  string            `json:"slot"`
}

// GearPreviewItem defines model for gear_preview_item.
type GearPreviewItem struct {
	DisplayName string                `json:"display_name"`
	Fingerprint string                `json:"fingerprint"`
	IconUrl     *string               `json:"icon_url"`
	ItemId      int                   `json:"item_id"`
	ItemLevel   *int                  `json:"item_level"`
	Name        string                `json:"name"`
	RawLine     string                `json:"raw_line"`
	Slot        string                `json:"slot"`
	Source      GearPreviewItemSource `json:"source"`
	WowheadData string                `json:"wowhead_data"`
	WowheadUrl  string                `json:"wowhead_url"`
}

// GearPreviewItemSource defines model for gear_preview_item_source.
type GearPreviewItemSource string

// GearPreviewRequest defines model for gear_preview_request.
type GearPreviewRequest struct {
	// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
	SimcAddonExport SimcAddonExport `json:"simc_addon_export"`
}

// GearPreviewResponse defines model for gear_preview_response.
type GearPreviewResponse struct {
	Groups []GearPreviewGroup `json:"groups"`
}

// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
type SimcAddonExport = string

// Simulation All details & data about a simulation.
type Simulation struct {
	// ErrorText Error message for the simulation job (if one occurred)
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation
	Id *string `json:"id,omitempty"`

	// SimResult The raw output / result of the simulation operation
	SimResult        *string           `json:"sim_result,omitempty"`
	SimulationStatus *SimulationStatus `json:"simulation_status,omitempty"`
}

// SimulationOptions Specifies simulation options to send to the API.
type SimulationOptions struct {
	// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
	SimcAddonExport SimcAddonExport `json:"simc_addon_export"`
}

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimcGearPreviewJSONRequestBody defines body for SimcGearPreview for application/json ContentType.
type SimcGearPreviewJSONRequestBody = GearPreviewRequest

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
