// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api_types

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AddonExportEquipmentSource.
const (
	Bag      AddonExportEquipmentSource = "bag"
	Equipped AddonExportEquipmentSource = "equipped"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

type AddonExport struct {
	ActiveTalents           *string                                 `json:"active_talents,omitempty"`
	AlternateTalentLoadouts []AddonExportAlternateTalentLoadout     `json:"alternate_talent_loadouts,omitempty"`
	CatalystCurrencies      map[string]int                          `json:"catalyst_currencies,omitempty"`
	CharacterName           *string                                 `json:"character_name,omitempty"`
	Checksum                *string                                 `json:"checksum,omitempty"`
	Class                   *string                                 `json:"class,omitempty"`
	Equipment               []AddonExportEquipmentItem              `json:"equipment,omitempty"`
	HeaderComment           *string                                 `json:"header_comment,omitempty"`
	LootSpec                *string                                 `json:"loot_spec,omitempty"`
	Professions             *string                                 `json:"professions,omitempty"`
	Race                    *string                                 `json:"race,omitempty"`
	Region                  *string                                 `json:"region,omitempty"`
	RequiredSimcComment     *string                                 `json:"required_simc_comment,omitempty"`
	Role                    *string                                 `json:"role,omitempty"`
	Server                  *string                                 `json:"server,omitempty"`
	SimcAddonComment        *string                                 `json:"simc_addon_comment,omitempty"`
	SlotHighWatermarks      map[string]AddonExportSlotHighWatermark `json:"slot_high_watermarks,omitempty"`
	Spec                    *string                                 `json:"spec,omitempty"`
	UpgradeAchievements     []int                                   `json:"upgrade_achievements,omitempty"`
	WowBuildComment         *string                                 `json:"wow_build_comment,omitempty"`
	Level                   *string                                 `json:"level,omitempty"`
}

type AddonExportAlternateTalentLoadout struct {
	Name    string `json:"name"`
	Talents string `json:"talents"`
}

type AddonExportEquipmentItem struct {
	BonusIds        []int                      `json:"bonus_ids,omitempty"`
	CraftedStats    []int                      `json:"crafted_stats,omitempty"`
	CraftingQuality *int                       `json:"crafting_quality,omitempty"`
	DisplayName     string                     `json:"display_name"`
	EnchantId       *int                       `json:"enchant_id,omitempty"`
	Fingerprint     string                     `json:"fingerprint"`
	GemIds          []int                      `json:"gem_ids,omitempty"`
	ItemId          int                        `json:"item_id"`
	ItemLevel       *int                       `json:"item_level,omitempty"`
	Name            string                     `json:"name"`
	RawLine         string                     `json:"raw_line"`
	Slot            string                     `json:"slot"`
	Source          AddonExportEquipmentSource `json:"source"`
}

type AddonExportEquipmentSource string

type AddonExportSlotHighWatermark struct {
	CurrentItemLevel int `json:"current_item_level"`
	MaxItemLevel     int `json:"max_item_level"`
}

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

type ParseAddonExportRequest struct {
	// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
	SimcAddonExport SimcAddonExport `json:"simc_addon_export"`
}

type ParseAddonExportResponse struct {
	AddonExport AddonExport `json:"addon_export"`
}

// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
type SimcAddonExport = string

// Simulation All details & data about a simulation.
type Simulation struct {
	// ErrorText Error message for the simulation job (if one occurred)
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation
	Id *string `json:"id,omitempty"`

	// SimResult The raw output / result of the simulation operation
	SimResult        *string           `json:"sim_result,omitempty"`
	SimulationStatus *SimulationStatus `json:"simulation_status,omitempty"`
}

// SimulationOptions Specifies simulation options to send to the API.
type SimulationOptions struct {
	// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
	SimcAddonExport SimcAddonExport `json:"simc_addon_export"`
}

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

type BadRequestError = ErrorResponse
type InternalError = ErrorResponse
type NotFoundError = ErrorResponse

// ParseAddonExportJSONRequestBody defines body for ParseAddonExport for application/json ContentType.
type ParseAddonExportJSONRequestBody = ParseAddonExportRequest

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
