// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api_types

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for SimulationStatus.
const (
	Complete   SimulationStatus = "complete"
	Error      SimulationStatus = "error"
	InProgress SimulationStatus = "in_progress"
	InQueue    SimulationStatus = "in_queue"
)

// ErrorResponse Error response returned by API when something goes wrong
type ErrorResponse struct {
	// Message Message explaining the error
	Message *string `json:"message,omitempty"`
}

// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
type SimcAddonExport = string

// Simulation All details & data about a simulation.
type Simulation struct {
	// ErrorText Error message for the simulation job (if one occurred)
	ErrorText *string `json:"error_text,omitempty"`

	// Id ID for the simulation operation
	Id *string `json:"id,omitempty"`

	// SimResult The raw output / result of the simulation operation
	SimResult        *string           `json:"sim_result,omitempty"`
	SimulationStatus *SimulationStatus `json:"simulation_status,omitempty"`
}

// SimulationOptions Specifies simulation options to send to the API.
type SimulationOptions struct {
	// SimcAddonExport Raw SimulationCraft addon export string supplied by the caller.
	SimcAddonExport SimcAddonExport `json:"simc_addon_export"`
}

// SimulationStatus defines model for simulation_status.
type SimulationStatus string

// BadRequestError Error response returned by API when something goes wrong
type BadRequestError = ErrorResponse

// InternalError Error response returned by API when something goes wrong
type InternalError = ErrorResponse

// NotFoundError Error response returned by API when something goes wrong
type NotFoundError = ErrorResponse

// SimulateJSONRequestBody defines body for Simulate for application/json ContentType.
type SimulateJSONRequestBody = SimulationOptions
