import { env } from "@/env";
import { createClient } from "./generated/client/client.gen";

/**
 * API client that tanstack backend uses to send requests to Saint API.
 * The underlying client is autogenerated, this file is not.
 */
export const saintApiClient = createClient({
	baseUrl: env.SAINT_API_URL,

	/**
	 * Tanstack backend uses an API key to authenticate
	 * with saint API currently.
	 */
	auth: env.SAINT_API_KEY,
});
