// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PrincipalType string

const (
	PrincipalTypeUser    PrincipalType = "user"
	PrincipalTypeService PrincipalType = "service"
)

func (e *PrincipalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalType(s)
	case string:
		*e = PrincipalType(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalType: %T", src)
	}
	return nil
}

type NullPrincipalType struct {
	PrincipalType PrincipalType
	Valid         bool // Valid is true if PrincipalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalType) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalType), nil
}

type SimulationKind string

const (
	SimulationKindBasic   SimulationKind = "basic"
	SimulationKindTopGear SimulationKind = "topGear"
)

func (e *SimulationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SimulationKind(s)
	case string:
		*e = SimulationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SimulationKind: %T", src)
	}
	return nil
}

type NullSimulationKind struct {
	SimulationKind SimulationKind
	Valid          bool // Valid is true if SimulationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSimulationKind) Scan(value interface{}) error {
	if value == nil {
		ns.SimulationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SimulationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSimulationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SimulationKind), nil
}

type SimulationStatus string

const (
	SimulationStatusInProgress SimulationStatus = "in_progress"
	SimulationStatusInQueue    SimulationStatus = "in_queue"
	SimulationStatusError      SimulationStatus = "error"
	SimulationStatusComplete   SimulationStatus = "complete"
)

func (e *SimulationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SimulationStatus(s)
	case string:
		*e = SimulationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SimulationStatus: %T", src)
	}
	return nil
}

type NullSimulationStatus struct {
	SimulationStatus SimulationStatus
	Valid            bool // Valid is true if SimulationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSimulationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SimulationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SimulationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSimulationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SimulationStatus), nil
}

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           *string
	RefreshToken          *string
	IdToken               *string
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 *string
	Password              *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ApiKey struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	VisibleHint string
	SecretHash  string
	PrincipalID uuid.UUID
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Principal struct {
	ID            uuid.UUID
	ServiceID     *uuid.UUID
	UserID        *string
	PrincipalType PrincipalType
}

type Service struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	Name      string
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IpAddress *string
	UserAgent *string
	UserId    string
}

type Simulation struct {
	ID           uuid.UUID
	OwnerID      *string
	Status       SimulationStatus
	Kind         SimulationKind
	SimConfig    []byte
	SimResult    []byte
	SimcRawJson2 []byte
	RawSimcInput *string
	ErrorText    *string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
