// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSimulation = `-- name: CreateSimulation :one
INSERT INTO public.simulation (sim_config, owner_id)
VALUES ($1, $2)
RETURNING id, owner_id, status, sim_config, sim_result, error_text, created_at, started_at, completed_at
`

type CreateSimulationParams struct {
	SimConfig []byte
	OwnerID   *string
}

func (q *Queries) CreateSimulation(ctx context.Context, arg CreateSimulationParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, createSimulation, arg.SimConfig, arg.OwnerID)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getApiKey = `-- name: GetApiKey :one
SELECT
    api_keys.secret_hash,
    principals.id AS principal_id,
    principals.principal_type,
    principals.user_id,
    principals.service_id
FROM
    public.api_keys
    INNER JOIN public.principals ON principals.id = api_keys.principal_id
WHERE secret_hash = $1 LIMIT 1
`

type GetApiKeyRow struct {
	SecretHash    string
	PrincipalID   uuid.UUID
	PrincipalType PrincipalType
	UserID        *string
	ServiceID     *uuid.UUID
}

func (q *Queries) GetApiKey(ctx context.Context, secretHash string) (GetApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getApiKey, secretHash)
	var i GetApiKeyRow
	err := row.Scan(
		&i.SecretHash,
		&i.PrincipalID,
		&i.PrincipalType,
		&i.UserID,
		&i.ServiceID,
	)
	return i, err
}

const getJwkByID = `-- name: GetJwkByID :one
SELECT id, "publicKey", "privateKey", "createdAt", "expiresAt"
FROM public.jwks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJwkByID(ctx context.Context, id string) (Jwk, error) {
	row := q.db.QueryRow(ctx, getJwkByID, id)
	var i Jwk
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSimulation = `-- name: GetSimulation :one
SELECT id, owner_id, status, sim_config, sim_result, error_text, created_at, started_at, completed_at
FROM public.simulation
WHERE id = $1
`

func (q *Queries) GetSimulation(ctx context.Context, id uuid.UUID) (Simulation, error) {
	row := q.db.QueryRow(ctx, getSimulation, id)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSimulationOptions = `-- name: GetSimulationOptions :one
SELECT sim_config 
FROM public.simulation
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSimulationOptions(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSimulationOptions, id)
	var sim_config []byte
	err := row.Scan(&sim_config)
	return sim_config, err
}

const listenNewSimulationData = `-- name: ListenNewSimulationData :exec
LISTEN new_simulation_data
`

func (q *Queries) ListenNewSimulationData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, listenNewSimulationData)
	return err
}

const updateSimulation = `-- name: UpdateSimulation :one
UPDATE public.simulation
SET
    sim_result = COALESCE($1, sim_result),
    error_text = COALESCE($2, error_text),
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at),
    status = COALESCE($5, status)
WHERE id = $6
RETURNING id, owner_id, status, sim_config, sim_result, error_text, created_at, started_at, completed_at
`

type UpdateSimulationParams struct {
	SimResult   *string
	ErrorText   *string
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	Status      NullSimulationStatus
	ID          uuid.UUID
}

func (q *Queries) UpdateSimulation(ctx context.Context, arg UpdateSimulationParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, updateSimulation,
		arg.SimResult,
		arg.ErrorText,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.ID,
	)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
