// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int32
	ApiKey      string
	ServiceName string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Simulation struct {
	ID          pgtype.UUID
	SimConfig   []byte
	SimResult   pgtype.Text
	ErrorText   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}
