// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IdToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ApiKey struct {
	ID        int32
	ApiKey    string
	CreatedAt pgtype.Timestamp
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserId    string
}

type Simulation struct {
	ID          pgtype.UUID
	SimConfig   []byte
	SimResult   pgtype.Text
	ErrorText   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	OwnerID     pgtype.Text
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
