// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PrincipalType string

const (
	PrincipalTypeUser    PrincipalType = "user"
	PrincipalTypeService PrincipalType = "service"
)

func (e *PrincipalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalType(s)
	case string:
		*e = PrincipalType(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalType: %T", src)
	}
	return nil
}

type NullPrincipalType struct {
	PrincipalType PrincipalType
	Valid         bool // Valid is true if PrincipalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalType) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalType), nil
}

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IdToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ApiKey struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	VisibleHint string
	SecretHash  string
	PrincipalID uuid.UUID
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Principal struct {
	ID            uuid.UUID
	ServiceID     *uuid.UUID
	UserID        *string
	PrincipalType PrincipalType
}

type Service struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Name      string
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserId    string
}

type Simulation struct {
	ID          pgtype.UUID
	SimConfig   []byte
	SimResult   pgtype.Text
	ErrorText   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	OwnerID     pgtype.Text
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
