// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSimulation = `-- name: CreateSimulation :one
INSERT INTO public.simulation (sim_config, owner_id)
VALUES ($1, $2)
RETURNING id, sim_config, sim_result, error_text, created_at, started_at, completed_at, owner_id
`

type CreateSimulationParams struct {
	SimConfig []byte
	OwnerID   pgtype.Text
}

func (q *Queries) CreateSimulation(ctx context.Context, arg CreateSimulationParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, createSimulation, arg.SimConfig, arg.OwnerID)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OwnerID,
	)
	return i, err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, created_at, updated_at, last_used_at, visible_hint, secret_hash, principal_id FROM public.api_keys
WHERE secret_hash = $1 LIMIT 1
`

func (q *Queries) GetApiKey(ctx context.Context, secretHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKey, secretHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.VisibleHint,
		&i.SecretHash,
		&i.PrincipalID,
	)
	return i, err
}

const getJwkByID = `-- name: GetJwkByID :one
SELECT id, "publicKey", "privateKey", "createdAt", "expiresAt"
FROM public.jwks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJwkByID(ctx context.Context, id string) (Jwk, error) {
	row := q.db.QueryRow(ctx, getJwkByID, id)
	var i Jwk
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSimulation = `-- name: GetSimulation :one
SELECT id, sim_config, sim_result, error_text, created_at, started_at, completed_at, owner_id
FROM public.simulation
WHERE id = $1
`

func (q *Queries) GetSimulation(ctx context.Context, id pgtype.UUID) (Simulation, error) {
	row := q.db.QueryRow(ctx, getSimulation, id)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OwnerID,
	)
	return i, err
}

const getSimulationOptions = `-- name: GetSimulationOptions :one
SELECT sim_config 
FROM public.simulation
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSimulationOptions(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSimulationOptions, id)
	var sim_config []byte
	err := row.Scan(&sim_config)
	return sim_config, err
}

const listenNewSimulationData = `-- name: ListenNewSimulationData :exec
LISTEN new_simulation_data
`

func (q *Queries) ListenNewSimulationData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, listenNewSimulationData)
	return err
}

const updateSimulation = `-- name: UpdateSimulation :one
UPDATE public.simulation
SET
    sim_result = COALESCE($1, sim_result),
    error_text = COALESCE($2, error_text),
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at)
WHERE id = $5
RETURNING id, sim_config, sim_result, error_text, created_at, started_at, completed_at, owner_id
`

type UpdateSimulationParams struct {
	SimResult   pgtype.Text
	ErrorText   pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	ID          pgtype.UUID
}

func (q *Queries) UpdateSimulation(ctx context.Context, arg UpdateSimulationParams) (Simulation, error) {
	row := q.db.QueryRow(ctx, updateSimulation,
		arg.SimResult,
		arg.ErrorText,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Simulation
	err := row.Scan(
		&i.ID,
		&i.SimConfig,
		&i.SimResult,
		&i.ErrorText,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OwnerID,
	)
	return i, err
}
