openapi: 3.0.3
info:
  title: Saint API
  version: 1.0.0
  description: |-
    This API responsible for the saint business logic. The discord bot, and, potentially more services in the future, will call this API.
paths:
  /add:
    post:
      operationId: add
      requestBody:
        description: Add two numbers together
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Add"
      responses:
        "200":
          description: Addition was completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddResponse"
  /simulate:
    post:
      operationId: simulate
      requestBody:
        description: "Simulate character dps"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimulationOptions"
      responses:
        "200":
          description: Simulation request was received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationResponse"
components:
  schemas:
    Add:
      type: object
      properties:
        a:
          type: integer
          format: int64
          example: 10
        b:
          type: integer
          format: int64
          example: -12
    AddResponse:
      type: object
      properties:
        result:
          type: integer
          format: int64
          example: 3
    SimulationOptions:
      type: object
      properties:
        character_realm:
          type: string
          description: WoW realm of the character we want to sim
        sim_config:
          nullable: true
          type: object
          description: Extra configuration options for sims

          properties:
            target_count:
              type: integer
              minimum: 1
              maximum: 10
              description: The amount of enemy targets to include in the sim
    SimulationResponse:
      type: object
      description: Object containing information about a simulation operation
      properties:
        simulation_id:
          type: string
