openapi: 3.0.3
info:
  title: Saint API
  version: 1.0.0
  description: |-
    This API responsible for the saint business logic. The discord bot, and, potentially more services in the future, will call this API.
paths:
  /simulate:
    post:
      operationId: simulate
      requestBody:
        description: "Simulate character dps"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimulationOptions"
      responses:
        "200":
          description: Simulation request was received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationResponse"
components:
  schemas:
    WoWCharacter:
      type: object
      description: Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc.
      properties:
        region:
          type: string
          description: Identifies the region in which the characters realm is located
          example: us
        realm:
          type: string
          description: The realm which the character is located on
          example: Hydraxis
        character_name:
          type: string
          description: The name of the WoW character
          example: John
          minLength: 2
          maxLength: 12

    SimulationOptions:
      type: object
      description: Specifices sim options, and the character of interest to sim
      properties:
        wow_character:
          $ref: "#/components/schemas/WoWCharacter"

    SimulationResponse:
      type: object
      description: Object containing information about a simulation operation
      properties:
        simulation_id:
          type: string
          description: Used to identify the ID of the sim in postgres, query this to read sim results
