# https://swagger.io/specification/
openapi: 3.0.3
info:
  title: Saint API
  version: 1.0.0
  description: |-
    This API responsible for the saint business logic. The discord bot, and, potentially more services in the future, will call this API.

paths:
  /simulation/{id}:
    get:
      description: View the result of a simulation.
      parameters:
        - name: id
          in: path
          description: The ID of the simulation to query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: The simulation result, or, if the simulation is currently in progress, the current state of the simulation job.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/simulation"
        "404":
          $ref: "#/components/responses/not_found_error"
        "500":
          $ref: "#/components/responses/internal_error"
  /simulation:
    post:
      operationId: simulate
      description: Request a simulation, powered by SimC.
      requestBody:
        required: true
        description: "Specify simulation options and wow characters here."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/simulation_options"
      security:
        - ApiKeyAuth: []
      responses:
        "202":
          description: Simulation request was accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_id:
                    type: string
                    description: ID of the simulation that was created
        "400":
          description: When one or more of the simulation options were invalid. For example, passing an invalid region or realm for the wow character may cause this.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
        "404":
          $ref: "#/components/responses/not_found_error"
        "500":
          $ref: "#/components/responses/internal_error"
components:
  responses:
    bad_request_error:
      description: Returned when the request is malformed or contains invalid input.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error_response"
    not_found_error:
      description: Returned when the api could not locate a requested resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error_response"
    internal_error:
      description: Returned whenever an internal server error occurs. This usually means the cause for the error was out of the control of the caller.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error_response"
  securitySchemes:
    ApiKeyAuth:
      description: |
        Schema used by trusted clients that authenticate with our API.
        Use the `Api-Key: <api_key>` header to authenticate.
      type: apiKey
      in: header
      name: Api-Key
  schemas:
    wow_character:
      type: object
      description: Object containing all data needed to identify a WoW character, used to retrieve their gear and talents, etc. (Realm list here https://worldofwarcraft.blizzard.com/en-us/game/status/us)
      required:
        - region
        - realm
        - character_name
      properties:
        region:
          type: string
          description: Identifies the region in which the characters realm is located
          example: us
          enum:
            - us
            - eu
            - kr
            - tw
            - cn
        realm:
          type: string
          description: The realm which the character is located on
          example: hydraxis
          enum:
            - thrall
            - hydraxis
            - silvermoon
            - draenor
        character_name:
          type: string
          description: The name of the WoW character
          example: John
          minLength: 2
          maxLength: 12

    simulation_options:
      type: object
      description: Specifices sim options, and the character of interest to sim, send this to the api
      required:
        - wow_character
      properties:
        wow_character:
          $ref: "#/components/schemas/wow_character"

    simulation:
      type: object
      description: All details & data about a simulation.
      properties:
        id:
          type: string
          description: ID for the simulation operation
          example: "41e9a22f-d2c1-48b2-b234-15db461049d4"
        simulation_status:
            $ref: "#/components/schemas/simulation_status"
        sim_result:
          type: string
          description: The raw output / result of the simulation operation
          example: "..."
        error_text:
          type: string
          description: Error message for the simulation job (if one occurred)

    simulation_status:
      type: string
      enum:
        - in_progress # currently being performed
        - in_queue # waiting to be picked up and in queue
        - error # failed
        - complete 

    error_response:
      type: object
      description: Error response returned by API when something goes wrong
      properties:
        message:
          type: string
          description: Message explaining the error
